// packages/vue/src/timer/timer.vue
<script setup lang="ts">
import { computed, provide, reactive } from "vue";
import { Timer as Ark } from "@ark-ui/vue/timer";
import {
  cn,
  timerActions,
  timerDefaults,
  timerDefaultUnits,
  type TimerRootProps,
} from "@75neo/themes";
import { timerVariantsKey } from "./variants";
import TimerActionTrigger from "./action-trigger.vue";
import TimerArea from "./area.vue";
import TimerControl from "./control.vue";
import TimerItem from "./item.vue";
import TimerSeparator from "./separator.vue";

/*
 * `showLabels` and `controls` default to on, so each is declared: without the
 * declaration Vue casts an absent boolean to `false` and the unit names and the
 * buttons vanish on a bare timer.
 */
const props = withDefaults(
  defineProps<
    TimerRootProps & {
      class?: unknown;
    }
  >(),
  { showLabels: true, controls: true, separator: ":" },
);

defineSlots<{
  default?: () => unknown;
}>();

// Getters, so a later prop change reaches already-mounted parts.
const resolved = reactive({
  get size() {
    return props.size ?? timerDefaults.size;
  },
});
provide(timerVariantsKey, resolved);

const rootClass = computed(() =>
  cn("flex min-w-0 flex-col gap-3", props.class as string | undefined),
);
const shown = computed(() => props.units ?? [...timerDefaultUnits]);
</script>

<template>
  <Ark.Root
    :auto-start="props.autoStart"
    :countdown="props.countdown"
    :interval="props.interval"
    :start-ms="props.startMs"
    :target-ms="props.targetMs"
    data-slot="timer"
    :data-size="resolved.size"
    :class="rootClass"
  >
    <template v-if="$slots.default">
      <slot />
    </template>
    <template v-else>
      <TimerArea>
        <template v-for="(unit, index) in shown" :key="unit">
          <TimerSeparator v-if="index > 0">{{ props.separator }}</TimerSeparator>
          <TimerItem :type="unit" :label="props.labels?.[unit]" :hide-label="!props.showLabels" />
        </template>
      </TimerArea>
      <TimerControl v-if="props.controls">
        <TimerActionTrigger
          v-for="entry in timerActions"
          :key="entry.action"
          :action="entry.action"
        >
          {{ entry.label }}
        </TimerActionTrigger>
      </TimerControl>
    </template>
  </Ark.Root>
</template>

// packages/react/src/timer/timer.tsx
import { Fragment } from "react";
import type React from "react";
import { Timer as Ark } from "@ark-ui/react/timer";
import {
  cn,
  timerActions,
  timerDefaults,
  timerDefaultUnits,
  type TimerRootProps as TimerContract,
  type TimerUnit,
} from "@75neo/themes";
import { TimerVariantsContext } from "./variants";
import { TimerActionTrigger } from "./action-trigger";
import { TimerArea } from "./area";
import { TimerControl } from "./control";
import { TimerItem } from "./item";
import { TimerSeparator } from "./separator";

export interface TimerProps
  extends
    Omit<React.HTMLAttributes<HTMLDivElement>, "dir">,
    Pick<
      React.ComponentProps<typeof Ark.Root>,
      | "autoStart"
      | "countdown"
      | "interval"
      | "startMs"
      | "targetMs"
      | "onComplete"
      | "onTick"
      | "ids"
    >,
    TimerContract {
  children?: React.ReactNode;
}

export function Timer({
  size,
  units,
  showLabels = true,
  labels,
  separator = ":",
  controls = true,
  autoStart,
  countdown,
  interval,
  startMs,
  targetMs,
  onComplete,
  onTick,
  ids,
  className,
  children,
  ...rest
}: TimerProps) {
  const resolved = { size: size ?? timerDefaults.size };
  const shown: TimerUnit[] = units ?? [...timerDefaultUnits];

  return (
    <TimerVariantsContext.Provider value={resolved}>
      <Ark.Root
        {...rest}
        autoStart={autoStart}
        countdown={countdown}
        interval={interval}
        startMs={startMs}
        targetMs={targetMs}
        onComplete={onComplete}
        onTick={onTick}
        ids={ids}
        data-slot="timer"
        data-size={resolved.size}
        className={cn("flex min-w-0 flex-col gap-3", className)}
      >
        {children ?? (
          <>
            <TimerArea>
              {shown.map((unit, index) => (
                <Fragment key={unit}>
                  {index > 0 && <TimerSeparator>{separator}</TimerSeparator>}
                  <TimerItem type={unit} label={labels?.[unit]} hideLabel={!showLabels} />
                </Fragment>
              ))}
            </TimerArea>
            {controls && (
              <TimerControl>
                {timerActions.map(({ action, label }) => (
                  <TimerActionTrigger key={action} action={action}>
                    {label}
                  </TimerActionTrigger>
                ))}
              </TimerControl>
            )}
          </>
        )}
      </Ark.Root>
    </TimerVariantsContext.Provider>
  );
}
