// src/components/vue/button/button.vue
<script setup lang="ts">
import { computed, type HTMLAttributes } from "vue";
import { cn } from "cn";
import { button, type ButtonVariants } from "@components/shared/button.styles";

interface ButtonProps {
  variant?: ButtonVariants["variant"];
  color?: ButtonVariants["color"];
  size?: ButtonVariants["size"];
  disabled?: ButtonVariants["disabled"];
  class?: HTMLAttributes["class"];
}

const props = defineProps<ButtonProps>();

defineSlots<{
  leading?: () => unknown;
  default?: () => unknown;
  trailing?: () => unknown;
}>();

const styles = computed(() =>
  button({
    variant: props.variant,
    color: props.color,
    size: props.size,
    disabled: props.disabled,
  }),
);
</script>

<template>
  <button :class="cn(styles.base(), props.class)" :disabled="disabled">
    <span v-if="$slots.leading" :class="styles.leadingIcon()">
      <slot name="leading" />
    </span>

    <slot />

    <span v-if="$slots.trailing" :class="styles.trailingIcon()">
      <slot name="trailing" />
    </span>
  </button>
</template>

// src/components/react/button/button.tsx
import React from "react";
import { cn } from "cn";
import { button, type ButtonVariants } from "@components/shared/button.styles";

export interface ButtonProps
  extends Omit<React.ComponentPropsWithRef<"button">, "color">, ButtonVariants {
  leading?: React.ReactNode;
  trailing?: React.ReactNode;
}

export default function Button({
  variant,
  color,
  size,
  disabled,
  leading,
  trailing,
  className,
  children,
  ...props
}: ButtonProps) {
  const { base, leadingIcon, trailingIcon } = button({ variant, color, size, disabled });

  return (
    <button className={cn(base(), className)} disabled={disabled} {...props}>
      {leading ? <span className={leadingIcon()}>{leading}</span> : null}
      {children}
      {trailing ? <span className={trailingIcon()}>{trailing}</span> : null}
    </button>
  );
}
