// packages/react/src/tooltip/tooltip.tsx
import type React from "react";
import { Tooltip as Ark } from "@ark-ui/react/tooltip";
import { tooltipDefaults, type TooltipRootProps as TooltipContract } from "@75neo/themes";
import { TooltipVariantsContext } from "./variants";
import { TooltipArrow } from "./arrow";
import { TooltipContent } from "./content";
import { TooltipTrigger } from "./trigger";

/**
 * Props for the Tooltip.
 *
 * @remarks
 * The open state comes from Ark, because React and Vue spell a controlled value too
 * differently to share one type. `children` is the trigger.
 */
export interface TooltipProps
  extends
    Pick<
      React.ComponentProps<typeof Ark.Root>,
      "open" | "defaultOpen" | "onOpenChange" | "ids" | "closeOnClick" | "closeOnEscape"
    >,
    TooltipContract {
  /** Render the bubble at the end of `body`. @defaultValue `true` */
  portal?: boolean;
  /** Reaches the bubble, which is the part a call site is naming. */
  className?: string;
  /** The element the bubble explains. It becomes the trigger. */
  children?: React.ReactNode;
}

export function Tooltip({
  size,
  text,
  arrow,
  placement,
  offset,
  openDelay,
  closeDelay,
  interactive,
  disabled,
  lazyMount,
  unmountOnExit,
  portal,
  open,
  defaultOpen,
  onOpenChange,
  closeOnClick,
  closeOnEscape,
  ids,
  className,
  children,
}: TooltipProps) {
  const resolved = { size: size ?? tooltipDefaults.size };

  return (
    <TooltipVariantsContext.Provider value={resolved}>
      <Ark.Root
        open={open}
        defaultOpen={defaultOpen}
        onOpenChange={onOpenChange}
        openDelay={openDelay}
        closeDelay={closeDelay}
        interactive={interactive}
        disabled={disabled}
        closeOnClick={closeOnClick}
        closeOnEscape={closeOnEscape}
        lazyMount={lazyMount}
        unmountOnExit={unmountOnExit}
        positioning={{ placement: placement ?? "top", offset: { mainAxis: offset ?? 8 } }}
        ids={ids}
      >
        {children != null && <TooltipTrigger>{children}</TooltipTrigger>}
        {text != null && (
          <TooltipContent portal={portal} className={className}>
            {(arrow ?? false) && <TooltipArrow />}
            {text}
          </TooltipContent>
        )}
      </Ark.Root>
    </TooltipVariantsContext.Provider>
  );
}

// packages/vue/src/tooltip/tooltip.vue
<script setup lang="ts">
import { computed, provide, reactive } from "vue";
import { Tooltip as Ark } from "@ark-ui/vue/tooltip";
import { tooltipDefaults, type TooltipRootProps } from "@75neo/themes";
import { tooltipVariantsKey } from "./variants";
import TooltipArrow from "./arrow.vue";
import TooltipContent from "./content.vue";
import TooltipTrigger from "./trigger.vue";

/*
 * `portal` defaults to on, so it is declared: without the declaration Vue casts an
 * absent boolean to `false` and the bubble stops leaving its clipping ancestor.
 */
const props = withDefaults(
  defineProps<
    TooltipRootProps & {
      /** Render the bubble at the end of `body`. @defaultValue `true` */
      portal?: boolean;
      class?: unknown;
    }
  >(),
  { portal: true, arrow: false, placement: "top", offset: 8 },
);

const open = defineModel<boolean | undefined>("open", { default: undefined });

defineSlots<{
  /** The element the bubble explains. It becomes the trigger. */
  default?: () => unknown;
}>();

// Getters, so a later prop change reaches already-mounted parts.
const resolved = reactive({
  get size() {
    return props.size ?? tooltipDefaults.size;
  },
});
provide(tooltipVariantsKey, resolved);

const positioning = computed(() => ({
  placement: props.placement,
  offset: { mainAxis: props.offset },
}));
</script>

<template>
  <Ark.Root
    v-model:open="open"
    :open-delay="props.openDelay"
    :close-delay="props.closeDelay"
    :interactive="props.interactive"
    :disabled="props.disabled"
    :lazy-mount="props.lazyMount"
    :unmount-on-exit="props.unmountOnExit"
    :positioning="positioning"
  >
    <TooltipTrigger v-if="$slots.default">
      <slot />
    </TooltipTrigger>
    <TooltipContent
      v-if="props.text != null"
      :portal="props.portal"
      :class="props.class as string | undefined"
    >
      <TooltipArrow v-if="props.arrow" />
      {{ props.text }}
    </TooltipContent>
  </Ark.Root>
</template>
