// packages/react/src/dialog/content.tsx
import type React from "react";
import { Dialog as Ark } from "@ark-ui/react/dialog";
import { cva } from "class-variance-authority";
import { Portal } from "@ark-ui/react/portal";
import {
  cn,
  dialogDefaults,
  dialogSizeData,
  type DialogContentProps as DialogContentContract,
} from "@75neo/themes";
import { useDialogVariants } from "./variants";

const dialogContent = cva("relative flex w-full flex-col overflow-hidden bg-default outline-none", {
  variants: {
    size: dialogSizeData.base,
    transition: {
      true: "data-[state=closed]:animate-panel-out data-[state=open]:animate-panel-in",
      false: "",
    },
    fullscreen: {
      true: "h-dvh max-h-dvh max-w-none rounded-none",
      false: "max-h-[calc(100dvh-2rem)] rounded-xl shadow-2xl ring ring-accented",
    },
  },
  defaultVariants: dialogDefaults,
});

export interface DialogContentProps
  extends React.ComponentProps<typeof Ark.Content>, DialogContentContract {
  /** Render the panel at the end of `body`. @defaultValue `true` */
  portal?: boolean;
}

export function DialogContent({
  transition,
  fullscreen,
  portal,
  className,
  children,
  ...rest
}: DialogContentProps) {
  const variants = useDialogVariants();
  const panel = (
    <Ark.Positioner
      data-slot="dialog-positioner"
      className={cn("fixed inset-0 flex items-center justify-center", fullscreen ? "p-0" : "p-4")}
    >
      <Ark.Content
        {...rest}
        data-slot="dialog-content"
        className={cn(dialogContent({ ...variants, transition, fullscreen }), className)}
      >
        {children}
      </Ark.Content>
    </Ark.Positioner>
  );

  if (portal ?? true) return <Portal>{panel}</Portal>;
  return panel;
}

// packages/vue/src/floating-panel/content.vue
<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { FloatingPanel as Ark } from "@ark-ui/vue/floating-panel";
import { cva } from "class-variance-authority";
import { cn, type FloatingPanelContentProps } from "@75neo/themes";

const floatingPanelContent = cva(
  "relative flex flex-col overflow-hidden rounded-xl bg-default shadow-lg ring ring-accented outline-none",
  {
    variants: {
      transition: {
        true: "data-[state=closed]:animate-panel-out data-[state=open]:animate-panel-in",
        false: "",
      },
    },
    defaultVariants: { transition: true },
  },
);

const props = withDefaults(
  defineProps<
    FloatingPanelContentProps & {
      class?: unknown;
      /** Render the panel at the end of `body`. @defaultValue `true` */
      portal?: boolean;
    }
  >(),
  { transition: true, portal: true },
);

defineSlots<{
  default?: () => unknown;
}>();

const contentClass = computed(() =>
  cn(floatingPanelContent({ transition: props.transition }), props.class as string | undefined),
);

/*
 * Gates the teleport below. Vue casts an absent Teleport target to nothing during the
 * server pass, so the popup is left in place until the component is mounted.
 */
const mounted = ref(false);
onMounted(() => {
  mounted.value = true;
});
</script>

<template>
  <Teleport to="body" :disabled="!props.portal || !mounted">
    <Ark.Positioner data-slot="floating-panel-positioner" class="z-50">
      <Ark.Content data-slot="floating-panel-content" :class="contentClass">
        <slot />
      </Ark.Content>
    </Ark.Positioner>
  </Teleport>
</template>
