// packages/react/src/floating-panel/floating-panel.tsx
import type React from "react";
import { FloatingPanel as Ark } from "@ark-ui/react/floating-panel";
import { ArrowDownLeft, GripVertical, Maximize2, Minus } from "lucide-react";
import {
  floatingPanelDefaults,
  floatingPanelResizeAxes,
  type FloatingPanelRootProps as FloatingPanelContract,
} from "@75neo/themes";
import { FloatingPanelVariantsContext } from "./variants";
import { FloatingPanelBody } from "./body";
import { FloatingPanelCloseTrigger } from "./close-trigger";
import { FloatingPanelContent } from "./content";
import { FloatingPanelControl } from "./control";
import { FloatingPanelDragTrigger } from "./drag-trigger";
import { FloatingPanelHeader } from "./header";
import { FloatingPanelResizeTrigger } from "./resize-trigger";
import { FloatingPanelStageTrigger } from "./stage-trigger";
import { FloatingPanelTitle } from "./title";

/**
 * Props for the FloatingPanel.
 *
 * @remarks
 * `title` is dropped from the HTML attributes, because the global attribute is the
 * wrong kind of title, and `dir` belongs to the locale provider.
 *
 * The open state comes from Ark, because React and Vue spell a controlled value too
 * differently to share one type. The pixel size reaches Ark as `size`, so the shared
 * contract names it `panelSize` and the `md` in the room stays the variant.
 *
 * `children` is the trigger, not the body: the body is data, and the one element a
 * caller has to own is what opens the panel.
 */
export interface FloatingPanelProps
  extends
    Omit<React.HTMLAttributes<HTMLDivElement>, "title" | "dir" | "draggable">,
    Pick<React.ComponentProps<typeof Ark.Root>, "open" | "defaultOpen" | "onOpenChange" | "ids">,
    FloatingPanelContract<React.ReactNode> {
  /** The element that opens the panel. It becomes the trigger. */
  children?: React.ReactNode;
}

export function FloatingPanel({
  size,
  transition,
  title,
  header,
  body,
  stages,
  close,
  closeIcon,
  dragIcon,
  minimizeIcon,
  maximizeIcon,
  restoreIcon,
  draggable,
  resizable,
  disabled,
  closeOnEscape,
  strategy,
  defaultPosition,
  defaultSize,
  panelSize,
  minSize,
  maxSize,
  persistRect,
  portal,
  lazyMount,
  unmountOnExit,
  children,
  open,
  defaultOpen,
  onOpenChange,
  ids,
  className,
  ...rest
}: FloatingPanelProps) {
  const resolved = { size: size ?? floatingPanelDefaults.size };

  return (
    <FloatingPanelVariantsContext.Provider value={resolved}>
      <Ark.Root
        {...rest}
        open={open}
        defaultOpen={defaultOpen}
        onOpenChange={onOpenChange}
        draggable={draggable}
        resizable={resizable}
        disabled={disabled}
        closeOnEscape={closeOnEscape}
        strategy={strategy}
        defaultPosition={defaultPosition}
        defaultSize={defaultSize}
        size={panelSize}
        minSize={minSize}
        maxSize={maxSize}
        persistRect={persistRect}
        lazyMount={lazyMount}
        unmountOnExit={unmountOnExit}
        ids={ids}
        data-slot="floating-panel"
        data-size={resolved.size}
      >
        {children != null && <Ark.Trigger asChild>{children}</Ark.Trigger>}
        <FloatingPanelContent portal={portal} transition={transition} className={className}>
          {header ?? (
            <FloatingPanelDragTrigger>
              <FloatingPanelHeader>
                {title != null && (
                  <FloatingPanelTitle>
                    {dragIcon ?? <GripVertical />}
                    {title}
                  </FloatingPanelTitle>
                )}
                <FloatingPanelControl>
                  {(stages ?? ["minimized", "maximized", "default"]).map((stage) => (
                    <FloatingPanelStageTrigger key={stage} stage={stage}>
                      {stage === "minimized"
                        ? (minimizeIcon ?? <Minus />)
                        : stage === "maximized"
                          ? (maximizeIcon ?? <Maximize2 />)
                          : (restoreIcon ?? <ArrowDownLeft />)}
                    </FloatingPanelStageTrigger>
                  ))}
                  {(close ?? true) && (
                    <FloatingPanelCloseTrigger aria-label="Close panel">
                      {closeIcon}
                    </FloatingPanelCloseTrigger>
                  )}
                </FloatingPanelControl>
              </FloatingPanelHeader>
            </FloatingPanelDragTrigger>
          )}
          {body != null && <FloatingPanelBody>{body}</FloatingPanelBody>}
          {(resizable ?? true) &&
            floatingPanelResizeAxes.map((axis) => (
              <FloatingPanelResizeTrigger key={axis} axis={axis} />
            ))}
        </FloatingPanelContent>
      </Ark.Root>
    </FloatingPanelVariantsContext.Provider>
  );
}

// packages/vue/src/floating-panel/floating-panel.vue
<script setup lang="ts">
import { type Component, provide, reactive } from "vue";
import { FloatingPanel as Ark } from "@ark-ui/vue/floating-panel";
import {
  ArrowDownLeft as ArrowDownLeftIcon,
  GripVertical as GripVerticalIcon,
  Maximize2 as Maximize2Icon,
  Minus as MinusIcon,
  X as XIcon,
} from "@lucide/vue";
import {
  floatingPanelDefaults,
  floatingPanelResizeAxes,
  type FloatingPanelRootProps,
} from "@75neo/themes";
import { floatingPanelVariantsKey } from "./variants";
import FloatingPanelBody from "./body.vue";
import FloatingPanelCloseTrigger from "./close-trigger.vue";
import FloatingPanelContent from "./content.vue";
import FloatingPanelControl from "./control.vue";
import FloatingPanelDragTrigger from "./drag-trigger.vue";
import FloatingPanelHeader from "./header.vue";
import FloatingPanelResizeTrigger from "./resize-trigger.vue";
import FloatingPanelStageTrigger from "./stage-trigger.vue";
import FloatingPanelTitle from "./title.vue";

/*
 * `draggable`, `resizable` and `close` default to on, so each is declared: without
 * the declaration Vue casts an absent boolean to `false` and the grip, the handles
 * and the cross vanish on a bare panel.
 */
const props = withDefaults(
  defineProps<
    FloatingPanelRootProps<Component> & {
      class?: unknown;
    }
  >(),
  { draggable: true, resizable: true, close: true },
);

const emit = defineEmits<{
  /** Fired when the panel opens or closes. */
  openChange: [details: { open: boolean }];
}>();

defineSlots<{
  /** The element that opens the panel. It becomes the trigger. */
  default?: () => unknown;
}>();

/*
 * `default: undefined` keeps an absent `v-model:open` absent. Without it the declared
 * prop would reach Ark as an explicit `false` and pin the panel shut, which would
 * leave `defaultOpen` with nothing to do.
 */
const open = defineModel<boolean | undefined>("open", { default: undefined });

// Getters, so a later prop change reaches already-mounted parts.
const resolved = reactive({
  get size() {
    return props.size ?? floatingPanelDefaults.size;
  },
});
provide(floatingPanelVariantsKey, resolved);
</script>

<template>
  <Ark.Root
    data-slot="floating-panel"
    :data-size="resolved.size"
    v-model:open="open"
    @open-change="emit('openChange', $event)"
    :draggable="props.draggable"
    :resizable="props.resizable"
    :disabled="props.disabled"
    :close-on-escape="props.closeOnEscape"
    :strategy="props.strategy"
    :default-position="props.defaultPosition"
    :default-size="props.defaultSize"
    :size="props.panelSize"
    :min-size="props.minSize"
    :max-size="props.maxSize"
    :persist-rect="props.persistRect"
    :lazy-mount="props.lazyMount"
    :unmount-on-exit="props.unmountOnExit"
  >
    <Ark.Trigger v-if="$slots.default" as-child>
      <slot />
    </Ark.Trigger>
    <FloatingPanelContent :portal="props.portal" :class="props.class as string | undefined">
      <component :is="props.header" v-if="props.header !== undefined" />
      <template v-else>
        <FloatingPanelDragTrigger>
          <FloatingPanelHeader>
            <FloatingPanelTitle v-if="props.title != null">
              <component :is="props.dragIcon ?? GripVerticalIcon" />
              {{ props.title }}
            </FloatingPanelTitle>
            <FloatingPanelControl>
              <FloatingPanelStageTrigger
                v-for="stage in props.stages ?? ['minimized', 'maximized', 'default']"
                :key="stage"
                :stage="stage"
              >
                <component
                  :is="
                    stage === 'minimized'
                      ? (props.minimizeIcon ?? MinusIcon)
                      : stage === 'maximized'
                        ? (props.maximizeIcon ?? Maximize2Icon)
                        : (props.restoreIcon ?? ArrowDownLeftIcon)
                  "
                />
              </FloatingPanelStageTrigger>
              <FloatingPanelCloseTrigger v-if="props.close" aria-label="Close panel">
                <component :is="props.closeIcon ?? XIcon" />
              </FloatingPanelCloseTrigger>
            </FloatingPanelControl>
          </FloatingPanelHeader>
        </FloatingPanelDragTrigger>
      </template>
      <FloatingPanelBody v-if="props.body != null">
        <component :is="props.body" />
      </FloatingPanelBody>
      <template v-if="props.resizable">
        <FloatingPanelResizeTrigger
          v-for="axis in floatingPanelResizeAxes"
          :key="axis"
          :axis="axis"
        />
      </template>
    </FloatingPanelContent>
  </Ark.Root>
</template>
