// registry/react/ui/slider/SliderRange.tsx
import React from "react";
import { Slider as Ark } from "@ark-ui/react/slider";
import { cn } from "cn";
import { sliderStyles as styles } from "@/registry/shared/lib/slider.styles";

export interface SliderRangeProps extends React.ComponentPropsWithRef<typeof Ark.Range> {}

export default function SliderRange({ className, ...props }: SliderRangeProps) {
  return <Ark.Range className={cn(styles.range(), className)} {...props} />;
}

// registry/vue/ui/slider/SliderRange.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { Slider as Ark } from "@ark-ui/vue/slider";
import { cn } from "cn";
import { sliderStyles as styles } from "@/registry/shared/lib/slider.styles";

interface SliderRangeProps {
  class?: HTMLAttributes["class"];
}

const props = defineProps<SliderRangeProps>();
</script>

<template>
  <Ark.Range :class="cn(styles.range(), props.class)" />
</template>
