// registry/react/ui/tour/TourTitle.tsx
import React from "react";
import { Tour as Ark } from "@ark-ui/react/tour";
import { cn } from "cn";
import { tour } from "@/registry/shared/lib/tour.styles";

export interface TourTitleProps extends React.ComponentPropsWithRef<typeof Ark.Title> {}

export default function TourTitle({ className, children, ...props }: TourTitleProps) {
  const styles = tour();

  return (
    <Ark.Title className={cn(styles.title(), className)} {...props}>
      {children}
    </Ark.Title>
  );
}

// registry/vue/ui/tour/TourTitle.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { Tour as Ark } from "@ark-ui/vue/tour";
import { cn } from "cn";
import { tour } from "@/registry/shared/lib/tour.styles";

interface TourTitleProps {
  class?: HTMLAttributes["class"];
}

const props = defineProps<TourTitleProps>();

const styles = tour();
</script>

<template>
  <Ark.Title :class="cn(styles.title(), props.class)" />
</template>
