// registry/vue/ui/date-picker/DatePickerView.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { DatePicker as Ark } from "@ark-ui/vue/date-picker";
import { cn } from "cn";
import { datePickerStyles as styles } from "@/registry/shared/lib/date-picker.styles";

interface DatePickerViewProps {
  view: "day" | "month" | "year";
  class?: HTMLAttributes["class"];
}

const props = defineProps<DatePickerViewProps>();

defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <Ark.View :view="props.view" :class="cn(styles.view(), props.class)">
    <slot />
  </Ark.View>
</template>

// registry/react/ui/date-picker/DatePickerView.tsx
import React from "react";
import { DatePicker as Ark } from "@ark-ui/react/date-picker";
import { cn } from "cn";
import { datePickerStyles as styles } from "@/registry/shared/lib/date-picker.styles";

export interface DatePickerViewProps extends React.ComponentPropsWithRef<typeof Ark.View> {}

export default function DatePickerView({ className, children, ...props }: DatePickerViewProps) {
  return (
    <Ark.View className={cn(styles.view(), className)} {...props}>
      {children}
    </Ark.View>
  );
}
