// packages/react/src/file-upload/file-upload.tsx
import type React from "react";
import { FileUpload as Ark } from "@ark-ui/react/file-upload";
import {
  cn,
  fileUploadDefaults,
  type FileUploadRootProps as FileUploadContract,
} from "@75neo/themes";
import { FileUploadVariantsContext } from "./variants";
import { FileUploadDropzone } from "./dropzone";
import { FileUploadItem } from "./item";
import { FileUploadItemGroup } from "./item-group";
import { FileUploadLabel } from "./label";
import { FileUploadTrigger } from "./trigger";

/**
 * Props for the FileUpload.
 *
 * @remarks
 * `color` is dropped from the HTML attributes: the legacy presentational attribute
 * would collide with the axis of the same name. The files come from Ark, because
 * React and Vue spell a controlled list too differently to share one type.
 */
export interface FileUploadProps
  extends
    Omit<React.HTMLAttributes<HTMLDivElement>, "color" | "dir">,
    Pick<
      React.ComponentProps<typeof Ark.Root>,
      "acceptedFiles" | "defaultAcceptedFiles" | "onFileChange" | "onFileReject" | "ids"
    >,
    FileUploadContract<React.ReactNode> {
  children?: React.ReactNode;
}

export function FileUpload({
  color,
  size,
  label,
  title,
  description,
  triggerLabel,
  accept,
  maxFiles,
  maxFileSize,
  minFileSize,
  allowDrop,
  directory,
  capture,
  preview = true,
  list = true,
  disabled,
  readOnly,
  invalid,
  required,
  name,
  locale,
  icon,
  deleteIcon,
  acceptedFiles,
  defaultAcceptedFiles,
  onFileChange,
  onFileReject,
  ids,
  className,
  children,
  ...rest
}: FileUploadProps) {
  const resolved = {
    color: color ?? fileUploadDefaults.color,
    size: size ?? fileUploadDefaults.size,
  };

  return (
    <FileUploadVariantsContext.Provider value={resolved}>
      <Ark.Root
        {...rest}
        acceptedFiles={acceptedFiles}
        defaultAcceptedFiles={defaultAcceptedFiles}
        onFileChange={onFileChange}
        onFileReject={onFileReject}
        accept={accept}
        maxFiles={maxFiles}
        maxFileSize={maxFileSize}
        minFileSize={minFileSize}
        allowDrop={allowDrop}
        directory={directory}
        capture={capture}
        disabled={disabled}
        readOnly={readOnly}
        invalid={invalid}
        required={required}
        name={name}
        locale={locale}
        ids={ids}
        data-slot="file-upload"
        data-color={resolved.color}
        data-size={resolved.size}
        className={cn("flex w-full min-w-0 flex-col gap-1.5", className)}
      >
        {children ?? (
          <>
            {label != null && <FileUploadLabel>{label}</FileUploadLabel>}
            <FileUploadDropzone title={title} description={description} icon={icon}>
              <FileUploadTrigger>{triggerLabel}</FileUploadTrigger>
            </FileUploadDropzone>
            {list && (
              <FileUploadItemGroup>
                <Ark.Context>
                  {(api) =>
                    api.acceptedFiles.map((file) => (
                      <FileUploadItem
                        key={`${file.name}-${file.size}-${file.lastModified}`}
                        file={file}
                        preview={preview}
                        deleteIcon={deleteIcon}
                      />
                    ))
                  }
                </Ark.Context>
              </FileUploadItemGroup>
            )}
          </>
        )}
        <Ark.HiddenInput />
      </Ark.Root>
    </FileUploadVariantsContext.Provider>
  );
}

// packages/vue/src/file-upload/file-upload.vue
<script setup lang="ts">
import { type Component, computed, provide, reactive } from "vue";
import { FileUpload as Ark } from "@ark-ui/vue/file-upload";
import { cn, fileUploadDefaults, type FileUploadRootProps } from "@75neo/themes";
import { fileUploadVariantsKey } from "./variants";
import FileUploadDropzone from "./dropzone.vue";
import FileUploadItem from "./item.vue";
import FileUploadItemGroup from "./item-group.vue";
import FileUploadLabel from "./label.vue";
import FileUploadTrigger from "./trigger.vue";

/*
 * `preview` and `list` default to on, so each is declared: without the declaration
 * Vue casts an absent boolean to `false` and both the thumbnails and the whole list
 * disappear from a bare uploader.
 */
const props = withDefaults(
  defineProps<
    FileUploadRootProps<Component> & {
      class?: unknown;
    }
  >(),
  { preview: true, list: true },
);

const files = defineModel<File[] | undefined>({ default: undefined });

defineSlots<{
  default?: () => unknown;
}>();

// Getters, so a later prop change reaches already-mounted parts.
const resolved = reactive({
  get color() {
    return props.color ?? fileUploadDefaults.color;
  },
  get size() {
    return props.size ?? fileUploadDefaults.size;
  },
});
provide(fileUploadVariantsKey, resolved);

const rootClass = computed(() =>
  cn("flex w-full min-w-0 flex-col gap-1.5", props.class as string | undefined),
);
</script>

<template>
  <Ark.Root
    v-model="files"
    :accept="props.accept"
    :max-files="props.maxFiles"
    :max-file-size="props.maxFileSize"
    :min-file-size="props.minFileSize"
    :allow-drop="props.allowDrop"
    :directory="props.directory"
    :capture="props.capture"
    :disabled="props.disabled"
    :read-only="props.readOnly"
    :invalid="props.invalid"
    :required="props.required"
    :name="props.name"
    :locale="props.locale"
    data-slot="file-upload"
    :data-color="resolved.color"
    :data-size="resolved.size"
    :class="rootClass"
  >
    <template v-if="$slots.default">
      <slot />
    </template>
    <template v-else>
      <FileUploadLabel v-if="props.label != null">{{ props.label }}</FileUploadLabel>
      <FileUploadDropzone :title="props.title" :description="props.description" :icon="props.icon">
        <FileUploadTrigger>
          {{ props.triggerLabel ?? "Choose a file" }}
        </FileUploadTrigger>
      </FileUploadDropzone>
      <FileUploadItemGroup v-if="props.list">
        <Ark.Context v-slot="api">
          <FileUploadItem
            v-for="file in api.acceptedFiles"
            :key="`${file.name}-${file.size}-${file.lastModified}`"
            :file="file"
            :preview="props.preview"
            :delete-icon="props.deleteIcon"
          />
        </Ark.Context>
      </FileUploadItemGroup>
    </template>
    <Ark.HiddenInput />
  </Ark.Root>
</template>
