// packages/react/src/color-picker/swatches.tsx
import type React from "react";
import { ColorPicker as Ark } from "@ark-ui/react/color-picker";
import { cva } from "class-variance-authority";
import { cn, colorPickerDefaults, colorPickerSizeData } from "@75neo/themes";
import { useColorPickerVariants } from "./variants";

const colorPickerSwatches = cva("flex flex-wrap", {
  variants: { size: colorPickerSizeData.swatches },
  defaultVariants: colorPickerDefaults,
});

export interface ColorPickerSwatchesProps extends React.ComponentProps<typeof Ark.SwatchGroup> {}

export function ColorPickerSwatches({ className, children, ...rest }: ColorPickerSwatchesProps) {
  const variants = useColorPickerVariants();

  return (
    <Ark.SwatchGroup
      {...rest}
      data-slot="color-picker-swatches"
      className={cn(colorPickerSwatches(variants), className)}
    >
      {children}
    </Ark.SwatchGroup>
  );
}

// packages/vue/src/color-picker/swatches.vue
<script setup lang="ts">
import { computed } from "vue";
import { ColorPicker as Ark } from "@ark-ui/vue/color-picker";
import { cva } from "class-variance-authority";
import { cn, colorPickerDefaults, colorPickerSizeData } from "@75neo/themes";
import { useColorPickerVariants } from "./variants";

const colorPickerSwatches = cva("flex flex-wrap", {
  variants: { size: colorPickerSizeData.swatches },
  defaultVariants: colorPickerDefaults,
});

const props = defineProps<{
  class?: unknown;
}>();

defineSlots<{
  default?: () => unknown;
}>();

const variants = useColorPickerVariants();
const cls = computed(() => cn(colorPickerSwatches(variants), props.class as string | undefined));
</script>

<template>
  <Ark.SwatchGroup data-slot="color-picker-swatches" :class="cls">
    <slot />
  </Ark.SwatchGroup>
</template>
