// registry/vue/ui/popover/PopoverContent.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { Popover as Ark } from "@ark-ui/vue/popover";
import { cn } from "cn";
import { popoverStyles as styles } from "@/registry/shared/lib/popover.styles";

interface PopoverContentProps {
  class?: HTMLAttributes["class"];
}

const props = defineProps<PopoverContentProps>();

defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <Ark.Content :class="cn(styles.content(), props.class)">
    <slot />
  </Ark.Content>
</template>

// registry/react/ui/popover/PopoverContent.tsx
import React from "react";
import { Popover as Ark } from "@ark-ui/react/popover";
import { cn } from "cn";
import { popoverStyles as styles } from "@/registry/shared/lib/popover.styles";

export interface PopoverContentProps extends React.ComponentPropsWithRef<typeof Ark.Content> {}

export default function PopoverContent({ className, children, ...props }: PopoverContentProps) {
  return (
    <Ark.Content className={cn(styles.content(), className)} {...props}>
      {children}
    </Ark.Content>
  );
}
