// packages/vue/src/navigation-menu/item.vue
<script setup lang="ts">
import { computed } from "vue";
import { NavigationMenu as Ark } from "@ark-ui/vue/navigation-menu";
import { cva } from "class-variance-authority";
import {
  cn,
  navigationMenuDefaults,
  navigationMenuOrientationData,
  type NavigationMenuItemProps,
} from "@75neo/themes";
import { useNavigationMenuVariants } from "./variants";

const navigationMenuItem = cva("relative flex min-w-0 shrink-0", {
  variants: { orientation: navigationMenuOrientationData.item },
  defaultVariants: navigationMenuDefaults,
});

const props = defineProps<
  NavigationMenuItemProps & {
    class?: unknown;
  }
>();

defineSlots<{
  default?: () => unknown;
}>();

const variants = useNavigationMenuVariants();
const itemClass = computed(() =>
  cn(navigationMenuItem({ orientation: variants.orientation }), props.class as string | undefined),
);
</script>

<template>
  <Ark.Item
    :value="props.value"
    :disabled="props.disabled"
    data-slot="navigation-menu-item"
    :class="itemClass"
  >
    <slot />
  </Ark.Item>
</template>

// packages/react/src/accordion/item.tsx
import type React from "react";
import { Accordion as Ark } from "@ark-ui/react/accordion";
import { cva } from "class-variance-authority";
import {
  accordionDefaults,
  accordionVariantData,
  cn,
  type AccordionItemProps as AccordionItemContract,
} from "@75neo/themes";
import { useAccordionVariants } from "./variants";

const accordionItem = cva(
  "min-w-0 [overflow-anchor:none] group-data-[orientation=horizontal]/accordion:flex",
  {
    variants: { variant: accordionVariantData.item },
    defaultVariants: accordionDefaults,
  },
);

export interface AccordionItemProps
  extends React.ComponentProps<typeof Ark.Item>, AccordionItemContract {}

export function AccordionItem({
  value,
  disabled,
  className,
  children,
  ...rest
}: AccordionItemProps) {
  const variants = useAccordionVariants();

  return (
    <Ark.Item
      {...rest}
      value={value}
      disabled={disabled}
      data-slot="accordion-item"
      className={cn(accordionItem(variants), className)}
    >
      {children}
    </Ark.Item>
  );
}
