// registry/react/ui/accordion/AccordionItemTrigger.tsx
import React from "react";
import { Accordion as Ark } from "@ark-ui/react/accordion";
import { cn } from "cn";
import { accordionStyles as styles } from "@/registry/shared/lib/accordion.styles";

export interface AccordionItemTriggerProps extends React.ComponentPropsWithRef<
  typeof Ark.ItemTrigger
> {}

export default function AccordionItemTrigger({
  className,
  children,
  ...props
}: AccordionItemTriggerProps) {
  return (
    <Ark.ItemTrigger className={cn(styles.itemTrigger(), className)} {...props}>
      {children}
    </Ark.ItemTrigger>
  );
}

// registry/vue/ui/accordion/AccordionItemTrigger.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { Accordion as Ark } from "@ark-ui/vue/accordion";
import { cn } from "cn";
import { accordionStyles as styles } from "@/registry/shared/lib/accordion.styles";

interface AccordionItemTriggerProps {
  class?: HTMLAttributes["class"];
}

const props = defineProps<AccordionItemTriggerProps>();

defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <Ark.ItemTrigger :class="cn(styles.itemTrigger(), props.class)">
    <slot />
  </Ark.ItemTrigger>
</template>
