// registry/react/ui/field/FieldTextarea.tsx
import React from "react";
import { Field as Ark } from "@ark-ui/react/field";
import { cn } from "cn";
import { fieldStyles as styles } from "@/registry/shared/lib/field.styles";

export interface FieldTextareaProps extends React.ComponentPropsWithRef<typeof Ark.Textarea> {}

export default function FieldTextarea({ className, ...props }: FieldTextareaProps) {
  return <Ark.Textarea className={cn(styles.textarea(), className)} {...props} />;
}

// registry/vue/ui/field/FieldTextarea.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { Field as Ark } from "@ark-ui/vue/field";
import { cn } from "cn";
import { fieldStyles as styles } from "@/registry/shared/lib/field.styles";

interface FieldTextareaProps {
  class?: HTMLAttributes["class"];
}

const props = defineProps<FieldTextareaProps>();
</script>

<template>
  <Ark.Textarea :class="cn(styles.textarea(), props.class)" />
</template>
