// registry/vue/ui/navigation-menu/NavigationMenuTrigger.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { NavigationMenu as Ark } from "@ark-ui/vue/navigation-menu";
import { cn } from "cn";
import { navigationMenuStyles as styles } from "@/registry/shared/lib/navigation-menu.styles";

interface NavigationMenuTriggerProps {
  disabled?: boolean;
  class?: HTMLAttributes["class"];
}

const props = defineProps<NavigationMenuTriggerProps>();

defineSlots<{
  leading?: () => unknown;
  default?: () => unknown;
  trailing?: () => unknown;
}>();
</script>

<template>
  <Ark.Trigger :disabled="props.disabled" :class="cn(styles.trigger(), props.class)">
    <span v-if="$slots.leading" :class="styles.triggerLeading()">
      <slot name="leading" />
    </span>

    <slot />

    <span v-if="$slots.trailing" :class="styles.triggerTrailing()">
      <slot name="trailing" />
    </span>
  </Ark.Trigger>
</template>

// registry/react/ui/navigation-menu/NavigationMenuTrigger.tsx
import React from "react";
import { NavigationMenu as Ark } from "@ark-ui/react/navigation-menu";
import { cn } from "cn";
import { navigationMenuStyles as styles } from "@/registry/shared/lib/navigation-menu.styles";

export interface NavigationMenuTriggerProps extends React.ComponentPropsWithRef<
  typeof Ark.Trigger
> {
  leading?: React.ReactNode;
  trailing?: React.ReactNode;
}

export default function NavigationMenuTrigger({
  leading,
  trailing,
  className,
  children,
  ...props
}: NavigationMenuTriggerProps) {
  return (
    <Ark.Trigger className={cn(styles.trigger(), className)} {...props}>
      {leading ? <span className={styles.triggerLeading()}>{leading}</span> : null}
      {children}
      {trailing ? <span className={styles.triggerTrailing()}>{trailing}</span> : null}
    </Ark.Trigger>
  );
}
