// packages/react/src/header/header.tsx
import { useState } from "react";
import type React from "react";
import { Dialog as Ark } from "@ark-ui/react/dialog";
import {
  cn,
  headerClasses,
  headerDefaults,
  type HeaderRootProps as HeaderContract,
} from "@75neo/themes";
import { HeaderVariantsContext } from "./variants";
import { HeaderCenter } from "./center";
import { HeaderEnd } from "./end";
import { HeaderMenu } from "./menu";
import { HeaderRow } from "./row";
import { HeaderStart } from "./start";
import { HeaderTitle } from "./title";
import { HeaderToggle } from "./toggle";

/**
 * Props for the Header.
 *
 * @remarks
 * `title` is dropped from the HTML attributes, because the global attribute is a
 * tooltip where this one is the wordmark. `children` is the centre of the bar, which
 * is the region a header with one navigation in it should use.
 */
export interface HeaderProps
  extends Omit<React.HTMLAttributes<HTMLElement>, "title">, HeaderContract<React.ReactNode> {
  /** The middle of the bar, usually a navigation. Hidden on a narrow viewport. */
  children?: React.ReactNode;
  /** The start of the bar. Falls back to the wordmark. */
  start?: React.ReactNode;
  /** The end of the bar, usually a set of actions. */
  end?: React.ReactNode;
  /** The menu's content on a narrow viewport. Without it there is no menu. */
  menu?: React.ReactNode;
  /** Whether the menu is open. Leave it out to let the Header keep the state. */
  open?: boolean;
  /** The starting state when the Header keeps it. */
  defaultOpen?: boolean;
  /** Fired whenever the menu opens or closes. */
  onOpenChange?: (details: { open: boolean }) => void;
}

/**
 * The bar across the top of a page, and the menu it opens where there is no room for
 * a navigation.
 *
 * @remarks
 * The wordmark and the actions render twice, once in the bar and once at the top of
 * the menu, so the menu opens over the page without the page appearing to lose its
 * header.
 */
export function Header({
  toggleSide = headerDefaults.toggleSide,
  title,
  href,
  toggle = true,
  toggleIcon,
  toggleCloseIcon,
  overlay = true,
  portal = true,
  children,
  start,
  end,
  menu,
  open,
  defaultOpen,
  onOpenChange,
  className,
  ...rest
}: HeaderProps) {
  const [uncontrolled, setUncontrolled] = useState(defaultOpen ?? false);
  const isOpen = open ?? uncontrolled;

  /*
   * Ark reports its own dismissals through `onOpenChange`, so routing the toggle
   * through one setter keeps a single path in and out: the button writes the state,
   * Ark reads it, and Escape or a click outside comes back here.
   */
  const setOpen = (next: boolean) => {
    if (open === undefined) setUncontrolled(next);
    onOpenChange?.({ open: next });
  };

  const hasMenu = toggle && menu != null;
  const toggleButton = hasMenu && (
    <HeaderToggle openIcon={toggleIcon} closeIcon={toggleCloseIcon} />
  );

  const startRegion = (
    <HeaderStart>
      {toggleSide === "start" && toggleButton}
      {start ?? (title != null && <HeaderTitle href={href}>{title}</HeaderTitle>)}
    </HeaderStart>
  );

  const endRegion = (
    <HeaderEnd>
      {end}
      {toggleSide === "end" && toggleButton}
    </HeaderEnd>
  );

  return (
    <HeaderVariantsContext.Provider value={{ toggleSide, open: isOpen, setOpen, title }}>
      <Ark.Root open={isOpen} onOpenChange={(details) => setOpen(details.open)} lazyMount>
        <header {...rest} data-slot="header" className={cn(headerClasses.root, className)}>
          <HeaderRow>
            {startRegion}
            <HeaderCenter>{children}</HeaderCenter>
            {endRegion}
          </HeaderRow>
        </header>

        {hasMenu && (
          <HeaderMenu
            overlay={overlay}
            portal={portal}
            label={title ?? "Menu"}
            header={
              <>
                {startRegion}
                {endRegion}
              </>
            }
          >
            {menu}
          </HeaderMenu>
        )}
      </Ark.Root>
    </HeaderVariantsContext.Provider>
  );
}

// packages/vue/src/header/header.vue
<script setup lang="ts">
import { type Component, computed, provide, reactive, ref } from "vue";
import { Dialog as Ark } from "@ark-ui/vue/dialog";
import { cn, headerClasses, headerDefaults, type HeaderRootProps } from "@75neo/themes";
import { headerVariantsKey } from "./variants";
import HeaderCenter from "./center.vue";
import HeaderEnd from "./end.vue";
import HeaderMenu from "./menu.vue";
import HeaderRow from "./row.vue";
import HeaderStart from "./start.vue";
import HeaderTitle from "./title.vue";
import HeaderToggle from "./toggle.vue";

/*
 * `toggle`, `overlay` and `portal` default to on, so each is declared: without the
 * declaration Vue casts an absent boolean to `false` and the menu button, the scrim
 * and the teleport all vanish from a bare header.
 */
const props = withDefaults(
  defineProps<
    HeaderRootProps<Component> & {
      class?: unknown;
    }
  >(),
  { toggle: true, overlay: true, portal: true, toggleSide: headerDefaults.toggleSide },
);

const open = defineModel<boolean>("open", { default: false });

const slots = defineSlots<{
  /** The middle of the bar, usually a navigation. Hidden on a narrow viewport. */
  default?: () => unknown;
  /** The start of the bar. Falls back to the wordmark. */
  start?: () => unknown;
  /** The end of the bar, usually a set of actions. */
  end?: () => unknown;
  /** The menu's content on a narrow viewport. Without it there is no menu. */
  menu?: () => unknown;
}>();

// Getters, so a later prop change reaches already-mounted parts.
const resolved = reactive({
  get toggleSide() {
    return props.toggleSide;
  },
  get open() {
    return open.value;
  },
  setOpen: (next: boolean) => {
    open.value = next;
  },
  get title() {
    return props.title;
  },
});
provide(headerVariantsKey, resolved);

const rootClass = computed(() => cn(headerClasses.root, props.class as string | undefined));
const hasMenu = computed(() => props.toggle && slots.menu != null);
const lazy = ref(true);
</script>

<template>
  <Ark.Root v-model:open="open" :lazy-mount="lazy">
    <header data-slot="header" :class="rootClass">
      <HeaderRow>
        <HeaderStart>
          <HeaderToggle
            v-if="hasMenu && resolved.toggleSide === 'start'"
            :open-icon="props.toggleIcon"
            :close-icon="props.toggleCloseIcon"
          />
          <slot v-if="$slots.start" name="start" />
          <HeaderTitle v-else-if="props.title != null" :href="props.href">
            {{ props.title }}
          </HeaderTitle>
        </HeaderStart>
        <HeaderCenter>
          <slot />
        </HeaderCenter>
        <HeaderEnd>
          <slot name="end" />
          <HeaderToggle
            v-if="hasMenu && resolved.toggleSide === 'end'"
            :open-icon="props.toggleIcon"
            :close-icon="props.toggleCloseIcon"
          />
        </HeaderEnd>
      </HeaderRow>
    </header>

    <HeaderMenu
      v-if="hasMenu"
      :overlay="props.overlay"
      :portal="props.portal"
      :label="props.title ?? 'Menu'"
    >
      <template #header>
        <HeaderStart>
          <HeaderToggle
            v-if="resolved.toggleSide === 'start'"
            :open-icon="props.toggleIcon"
            :close-icon="props.toggleCloseIcon"
          />
          <slot v-if="$slots.start" name="start" />
          <HeaderTitle v-else-if="props.title != null" :href="props.href">
            {{ props.title }}
          </HeaderTitle>
        </HeaderStart>
        <HeaderEnd>
          <slot name="end" />
          <HeaderToggle
            v-if="resolved.toggleSide === 'end'"
            :open-icon="props.toggleIcon"
            :close-icon="props.toggleCloseIcon"
          />
        </HeaderEnd>
      </template>
      <slot name="menu" />
    </HeaderMenu>
  </Ark.Root>
</template>
