// registry/react/ui/color-picker/ColorPickerControl.tsx
import React from "react";
import { ColorPicker as Ark } from "@ark-ui/react/color-picker";
import { cn } from "cn";
import { colorPickerStyles as styles } from "@/registry/shared/lib/color-picker.styles";

export interface ColorPickerControlProps extends React.ComponentPropsWithRef<typeof Ark.Control> {}

export default function ColorPickerControl({
  className,
  children,
  ...props
}: ColorPickerControlProps) {
  return (
    <Ark.Control className={cn(styles.control(), className)} {...props}>
      {children}
    </Ark.Control>
  );
}

// registry/vue/ui/color-picker/ColorPickerControl.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { ColorPicker as Ark } from "@ark-ui/vue/color-picker";
import { cn } from "cn";
import { colorPickerStyles as styles } from "@/registry/shared/lib/color-picker.styles";

interface ColorPickerControlProps {
  class?: HTMLAttributes["class"];
}

const props = defineProps<ColorPickerControlProps>();

defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <Ark.Control :class="cn(styles.control(), props.class)">
    <slot />
  </Ark.Control>
</template>
