// registry/vue/ui/steps/StepsSeparator.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { Steps as Ark } from "@ark-ui/vue/steps";
import { cn } from "cn";
import { stepsStyles as styles } from "@/registry/shared/lib/steps.styles";

interface StepsSeparatorProps {
  class?: HTMLAttributes["class"];
}

const props = defineProps<StepsSeparatorProps>();
</script>

<template>
  <Ark.Separator :class="cn(styles.separator(), props.class)" />
</template>

// registry/react/ui/steps/StepsSeparator.tsx
import React from "react";
import { Steps as Ark } from "@ark-ui/react/steps";
import { cn } from "cn";
import { stepsStyles as styles } from "@/registry/shared/lib/steps.styles";

export interface StepsSeparatorProps extends Omit<
  React.ComponentPropsWithRef<typeof Ark.Separator>,
  "children"
> {}

export default function StepsSeparator({ className, ...props }: StepsSeparatorProps) {
  return <Ark.Separator className={cn(styles.separator(), className)} {...props} />;
}
