// packages/vue/src/footer/footer.vue
<script setup lang="ts">
import { cn } from "@75neo/themes";
import FooterBottom from "./bottom.vue";
import FooterCenter from "./center.vue";
import FooterEnd from "./end.vue";
import FooterRow from "./row.vue";
import FooterStart from "./start.vue";
import FooterTop from "./top.vue";

/*
 * The five regions are named slots, so the default slot is left free to compose the
 * parts directly. Filling it replaces the composed row rather than adding to it.
 */
const props = defineProps<{
  class?: unknown;
}>();

defineSlots<{
  /** Composes the parts directly, in place of the row. */
  default?: () => unknown;
  /** A full-width band above the row. */
  top?: () => unknown;
  /** The start of the row, usually a copyright line. */
  start?: () => unknown;
  /** The middle of the row, usually a short navigation. */
  center?: () => unknown;
  /** The end of the row, usually social or legal links. */
  end?: () => unknown;
  /** A full-width band below the row. */
  bottom?: () => unknown;
}>();
</script>

<template>
  <footer data-slot="footer" :class="cn(props.class as string | undefined)">
    <template v-if="$slots.default">
      <slot />
    </template>
    <template v-else>
      <FooterTop v-if="$slots.top">
        <slot name="top" />
      </FooterTop>
      <FooterRow>
        <FooterEnd>
          <slot name="end" />
        </FooterEnd>
        <FooterCenter>
          <slot name="center" />
        </FooterCenter>
        <FooterStart>
          <slot name="start" />
        </FooterStart>
      </FooterRow>
      <FooterBottom v-if="$slots.bottom">
        <slot name="bottom" />
      </FooterBottom>
    </template>
  </footer>
</template>

// packages/react/src/footer/footer.tsx
import type React from "react";
import { cn } from "@75neo/themes";
import { FooterBottom } from "./bottom";
import { FooterCenter } from "./center";
import { FooterEnd } from "./end";
import { FooterRow } from "./row";
import { FooterStart } from "./start";
import { FooterTop } from "./top";

/**
 * Props for the Footer.
 *
 * @remarks
 * The five regions are content the caller owns and each is a named prop, so
 * `children` is left free to compose the parts directly. Passing children replaces
 * the composed row rather than adding to it.
 */
export interface FooterProps extends React.HTMLAttributes<HTMLElement> {
  /** A full-width band above the row. */
  top?: React.ReactNode;
  /** The start of the row, usually a copyright line. */
  start?: React.ReactNode;
  /** The middle of the row, usually a short navigation. */
  center?: React.ReactNode;
  /** The end of the row, usually social or legal links. */
  end?: React.ReactNode;
  /** A full-width band below the row. */
  bottom?: React.ReactNode;
  children?: React.ReactNode;
}

export function Footer({
  top,
  start,
  center,
  end,
  bottom,
  className,
  children,
  ...rest
}: FooterProps) {
  return (
    <footer {...rest} data-slot="footer" className={cn(className)}>
      {children ?? (
        <>
          {top != null && <FooterTop>{top}</FooterTop>}
          <FooterRow>
            <FooterEnd>{end}</FooterEnd>
            <FooterCenter>{center}</FooterCenter>
            <FooterStart>{start}</FooterStart>
          </FooterRow>
          {bottom != null && <FooterBottom>{bottom}</FooterBottom>}
        </>
      )}
    </footer>
  );
}
