// registry/vue/ui/toc/TocTitle.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { Toc as Ark } from "@ark-ui/vue/toc";
import { cn } from "cn";
import { tocStyles as styles } from "@/registry/shared/lib/toc.styles";

interface TocTitleProps {
  class?: HTMLAttributes["class"];
}

const props = defineProps<TocTitleProps>();

defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <Ark.Title :class="cn(styles.title(), props.class)">
    <slot />
  </Ark.Title>
</template>

// registry/react/ui/toc/TocTitle.tsx
import React from "react";
import { Toc as Ark } from "@ark-ui/react/toc";
import { cn } from "cn";
import { tocStyles as styles } from "@/registry/shared/lib/toc.styles";

export interface TocTitleProps extends React.ComponentPropsWithRef<typeof Ark.Title> {}

export default function TocTitle({ className, children, ...props }: TocTitleProps) {
  return (
    <Ark.Title className={cn(styles.title(), className)} {...props}>
      {children}
    </Ark.Title>
  );
}
