// registry/react/ui/tags-input/TagsInputInput.tsx
import React from "react";
import { TagsInput as Ark } from "@ark-ui/react/tags-input";
import { cn } from "cn";
import { tagsInputStyles as styles } from "@/registry/shared/lib/tags-input.styles";

export interface TagsInputInputProps extends React.ComponentPropsWithRef<typeof Ark.Input> {}

export default function TagsInputInput({ className, ...props }: TagsInputInputProps) {
  return <Ark.Input className={cn(styles.input(), className)} {...props} />;
}

// registry/vue/ui/tags-input/TagsInputInput.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { TagsInput as Ark } from "@ark-ui/vue/tags-input";
import { cn } from "cn";
import { tagsInputStyles as styles } from "@/registry/shared/lib/tags-input.styles";

interface TagsInputInputProps {
  class?: HTMLAttributes["class"];
}

const props = defineProps<TagsInputInputProps>();
</script>

<template>
  <Ark.Input :class="cn(styles.input(), props.class)" />
</template>
