// registry/react/ui/qr-code/QrCodeDownloadTrigger.tsx
import React from "react";
import { QrCode as Ark } from "@ark-ui/react/qr-code";
import { cn } from "cn";
import { qrCodeStyles as styles } from "@/registry/shared/lib/qr-code.styles";

export interface QrCodeDownloadTriggerProps extends React.ComponentPropsWithRef<
  typeof Ark.DownloadTrigger
> {}

export default function QrCodeDownloadTrigger({
  className,
  children,
  ...props
}: QrCodeDownloadTriggerProps) {
  return (
    <Ark.DownloadTrigger className={cn(styles.downloadTrigger(), className)} {...props}>
      {children}
    </Ark.DownloadTrigger>
  );
}

// registry/vue/ui/qr-code/QrCodeDownloadTrigger.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { QrCode as Ark } from "@ark-ui/vue/qr-code";
import type { QrCodeDownloadTriggerProps as ArkDownloadTriggerProps } from "@ark-ui/vue/qr-code";
import { cn } from "cn";
import { qrCodeStyles as styles } from "@/registry/shared/lib/qr-code.styles";

interface QrCodeDownloadTriggerProps {
  fileName: string;
  mimeType: ArkDownloadTriggerProps["mimeType"];
  quality?: number;
  class?: HTMLAttributes["class"];
}

const props = defineProps<QrCodeDownloadTriggerProps>();

defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <Ark.DownloadTrigger
    :file-name="props.fileName"
    :mime-type="props.mimeType"
    :quality="props.quality"
    :class="cn(styles.downloadTrigger(), props.class)"
  >
    <slot />
  </Ark.DownloadTrigger>
</template>
