// packages/react/src/tour/title.tsx
import type React from "react";
import { Tour as Ark } from "@ark-ui/react/tour";
import { cva } from "class-variance-authority";
import { cn, tourDefaults, tourSizeData } from "@75neo/themes";
import { useTourVariants } from "./variants";

const tourTitle = cva("font-semibold text-highlighted", {
  variants: { size: tourSizeData.title },
  defaultVariants: tourDefaults,
});

export interface TourTitleProps extends React.ComponentProps<typeof Ark.Title> {
  children?: React.ReactNode;
}

export function TourTitle({ className, children, ...rest }: TourTitleProps) {
  const variants = useTourVariants();

  return (
    <Ark.Title {...rest} data-slot="tour-title" className={cn(tourTitle(variants), className)}>
      {children}
    </Ark.Title>
  );
}

// packages/vue/src/tour/title.vue
<script setup lang="ts">
import { computed } from "vue";
import { Tour as Ark } from "@ark-ui/vue/tour";
import { cva } from "class-variance-authority";
import { cn, tourDefaults, tourSizeData } from "@75neo/themes";
import { useTourVariants } from "./variants";

const tourTitle = cva("font-semibold text-highlighted", {
  variants: { size: tourSizeData.title },
  defaultVariants: tourDefaults,
});

const props = defineProps<{
  class?: unknown;
}>();

defineSlots<{
  default?: () => unknown;
}>();

const variants = useTourVariants();
const titleClass = computed(() => cn(tourTitle(variants), props.class as string | undefined));
</script>

<template>
  <Ark.Title data-slot="tour-title" :class="titleClass">
    <!-- Ark renders its own text when no slot arrives; an empty one crashes that fallback. -->
    <template v-if="$slots.default" #default>
      <slot />
    </template>
  </Ark.Title>
</template>
