// registry/vue/ui/carousel/CarouselItemGroup.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { Carousel as Ark } from "@ark-ui/vue/carousel";
import { cn } from "cn";
import { carouselStyles as styles } from "@/registry/shared/lib/carousel.styles";

interface CarouselItemGroupProps {
  class?: HTMLAttributes["class"];
}

const props = defineProps<CarouselItemGroupProps>();

defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <Ark.ItemGroup :class="cn(styles.itemGroup(), props.class)">
    <slot />
  </Ark.ItemGroup>
</template>

// registry/react/ui/carousel/CarouselItemGroup.tsx
import React from "react";
import { Carousel as Ark } from "@ark-ui/react/carousel";
import { cn } from "cn";
import { carouselStyles as styles } from "@/registry/shared/lib/carousel.styles";

export interface CarouselItemGroupProps extends React.ComponentPropsWithRef<typeof Ark.ItemGroup> {}

export default function CarouselItemGroup({
  className,
  children,
  ...props
}: CarouselItemGroupProps) {
  return (
    <Ark.ItemGroup className={cn(styles.itemGroup(), className)} {...props}>
      {children}
    </Ark.ItemGroup>
  );
}
