// registry/vue/ui/carousel/CarouselProgressText.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { Carousel as Ark } from "@ark-ui/vue/carousel";
import { cn } from "cn";
import { carouselStyles as styles } from "@/registry/shared/lib/carousel.styles";

interface CarouselProgressTextProps {
  class?: HTMLAttributes["class"];
}

const props = defineProps<CarouselProgressTextProps>();
</script>

<template>
  <Ark.ProgressText :class="cn(styles.progressText(), props.class)" />
</template>

// registry/react/ui/carousel/CarouselProgressText.tsx
import React from "react";
import { Carousel as Ark } from "@ark-ui/react/carousel";
import { cn } from "cn";
import { carouselStyles as styles } from "@/registry/shared/lib/carousel.styles";

export interface CarouselProgressTextProps extends Omit<
  React.ComponentPropsWithRef<typeof Ark.ProgressText>,
  "children"
> {}

export default function CarouselProgressText({ className, ...props }: CarouselProgressTextProps) {
  return <Ark.ProgressText className={cn(styles.progressText(), className)} {...props} />;
}
