// packages/react/src/navigation-menu/navigation-menu.tsx
import type React from "react";
import { NavigationMenu as Ark } from "@ark-ui/react/navigation-menu";
import {
  cn,
  navigationMenuDefaults,
  type NavigationMenuRootProps as NavigationMenuContract,
} from "@75neo/themes";
import { NavigationMenuVariantsContext } from "./variants";
import { NavigationMenuContent } from "./content";
import { NavigationMenuItem } from "./item";
import { NavigationMenuLink } from "./link";
import { NavigationMenuList } from "./list";
import { NavigationMenuTrigger } from "./trigger";

/**
 * Props for the NavigationMenu.
 *
 * @remarks
 * `color` is dropped from the HTML attributes: the legacy presentational attribute
 * would collide with the axis of the same name. The open row comes from Ark, because
 * React and Vue spell a controlled value too differently to share one type.
 */
export interface NavigationMenuProps
  extends
    Omit<React.HTMLAttributes<HTMLElement>, "color" | "defaultValue" | "dir">,
    Pick<React.ComponentProps<typeof Ark.Root>, "value" | "defaultValue" | "onValueChange" | "ids">,
    NavigationMenuContract<React.ReactNode> {
  children?: React.ReactNode;
}

export function NavigationMenu({
  color,
  size,
  orientation,
  items,
  trailingIcon,
  value,
  defaultValue,
  onValueChange,
  ids,
  className,
  children,
  ...rest
}: NavigationMenuProps) {
  const resolved = {
    color: color ?? navigationMenuDefaults.color,
    size: size ?? navigationMenuDefaults.size,
    orientation: orientation ?? navigationMenuDefaults.orientation,
  };

  return (
    <NavigationMenuVariantsContext.Provider value={resolved}>
      <Ark.Root
        {...rest}
        value={value}
        defaultValue={defaultValue}
        onValueChange={onValueChange}
        orientation={orientation}
        ids={ids}
        data-slot="navigation-menu"
        data-color={resolved.color}
        data-size={resolved.size}
        className={cn("relative flex w-full min-w-0", className)}
      >
        {children ??
          (items != null && (
            <NavigationMenuList>
              {items.map((item) => (
                <NavigationMenuItem key={item.value} value={item.value} disabled={item.disabled}>
                  {item.links != null ? (
                    <>
                      <NavigationMenuTrigger
                        disabled={item.disabled}
                        leadingIcon={item.icon}
                        trailingIcon={trailingIcon}
                      >
                        {item.label}
                      </NavigationMenuTrigger>
                      <NavigationMenuContent value={item.value}>
                        {item.links.map((link) => (
                          <NavigationMenuLink
                            key={link.href}
                            href={link.href}
                            title={link.title}
                            description={link.description}
                            leadingIcon={link.icon}
                            current={link.current}
                          />
                        ))}
                      </NavigationMenuContent>
                    </>
                  ) : (
                    <NavigationMenuLink href={item.href ?? "#"} current={item.current}>
                      {item.icon != null && (
                        <span
                          data-slot="navigation-menu-link-icon"
                          className="shrink-0 text-dimmed [&>svg]:size-full"
                        >
                          {item.icon}
                        </span>
                      )}
                      {item.label}
                    </NavigationMenuLink>
                  )}
                </NavigationMenuItem>
              ))}
            </NavigationMenuList>
          ))}
      </Ark.Root>
    </NavigationMenuVariantsContext.Provider>
  );
}

// packages/vue/src/navigation-menu/navigation-menu.vue
<script setup lang="ts">
import { type Component, computed, provide, reactive } from "vue";
import { NavigationMenu as Ark } from "@ark-ui/vue/navigation-menu";
import { cn, navigationMenuDefaults, type NavigationMenuRootProps } from "@75neo/themes";
import { navigationMenuVariantsKey } from "./variants";
import NavigationMenuContent from "./content.vue";
import NavigationMenuItem from "./item.vue";
import NavigationMenuLink from "./link.vue";
import NavigationMenuList from "./list.vue";
import NavigationMenuTrigger from "./trigger.vue";

const props = defineProps<
  NavigationMenuRootProps<Component> & {
    class?: unknown;
  }
>();

const value = defineModel<string | undefined>({ default: undefined });

defineSlots<{
  default?: () => unknown;
}>();

// Getters, so a later prop change reaches already-mounted parts.
const resolved = reactive({
  get color() {
    return props.color ?? navigationMenuDefaults.color;
  },
  get size() {
    return props.size ?? navigationMenuDefaults.size;
  },
  get orientation() {
    return props.orientation ?? navigationMenuDefaults.orientation;
  },
});
provide(navigationMenuVariantsKey, resolved);

const rootClass = computed(() =>
  cn("relative flex w-full min-w-0", props.class as string | undefined),
);
const items = computed(() => props.items ?? []);
</script>

<template>
  <Ark.Root
    v-model="value"
    :orientation="props.orientation"
    data-slot="navigation-menu"
    :data-color="resolved.color"
    :data-size="resolved.size"
    :class="rootClass"
  >
    <template v-if="$slots.default">
      <slot />
    </template>
    <NavigationMenuList v-else>
      <NavigationMenuItem
        v-for="item in items"
        :key="item.value"
        :value="item.value"
        :disabled="item.disabled"
      >
        <template v-if="item.links != null">
          <NavigationMenuTrigger :leading-icon="item.icon" :trailing-icon="props.trailingIcon">
            {{ item.label }}
          </NavigationMenuTrigger>
          <NavigationMenuContent :value="item.value">
            <NavigationMenuLink
              v-for="link in item.links"
              :key="link.href"
              :href="link.href"
              :title="link.title"
              :description="link.description"
              :leading-icon="link.icon"
              :current="link.current"
            />
          </NavigationMenuContent>
        </template>
        <NavigationMenuLink
          v-else
          :href="item.href ?? '#'"
          :leading-icon="item.icon"
          :current="item.current"
        >
          {{ item.label }}
        </NavigationMenuLink>
      </NavigationMenuItem>
    </NavigationMenuList>
  </Ark.Root>
</template>
