// packages/vue/src/components/Sidebar.vue
<script setup lang="ts">
import { type Component, computed, watch } from "vue";
import { X } from "@lucide/vue";
import { sidebar, sidebarMobileQuery, type SidebarProps, type SidebarState } from "@75neo/themes";
import { useMediaQuery } from "../composables/media";
import { useResolvedTheme } from "../composables/theme";

/**
 * A column beside the page that collapses to a strip or disappears, and slides in over
 * the page where there is no room beside it.
 *
 * @remarks
 * One state serves both viewports and the component moves it across when the viewport
 * crosses `lg`: entering the narrow one remembers where the wide one was and closes the
 * panel, and leaving it puts the remembered value back. Without that, a sidebar that is
 * expanded by design would cover a phone's content the moment the page loaded.
 *
 * The narrow panel is the same DOM as the wide column, moved. It is not a focus trap
 * and does not try to be; see the note on the recipe for why a layout element can
 * afford that and a Dialog cannot.
 */
const props = withDefaults(defineProps<SidebarProps<Component> & { class?: unknown }>(), {
  side: "start",
  variant: "sidebar",
  collapsible: "offcanvas",
  /*
   * Both default on, and a type-based `defineProps` declares them as Boolean props, so
   * Vue casts an absent one to `false`. Left unnamed, the sidebar would refuse to
   * animate and would open over a phone's content with no scrim behind it.
   */
  transition: true,
  overlay: true,
});

const slots = defineSlots<{
  /** The scrolling middle of the column, usually a navigation. */
  default?: () => unknown;
  /** A row along the bottom, usually an account or a theme switch. */
  footer?: () => unknown;
  /** Buttons in the header, beside the close button. */
  actions?: () => unknown;
}>();

/*
 * A boolean model needs both the `undefined` in its type and the default, or Vue casts
 * an unbound one to `false` and the sidebar starts collapsed. Open is the intended
 * starting state, so an unset model reads as expanded.
 */
const open = defineModel<boolean | undefined>("open", { default: undefined });

const isMobile = useMediaQuery(sidebarMobileQuery);
const collapses = computed(() => props.collapsible !== "none");
const isOpen = computed(() => (collapses.value ? (open.value ?? true) : true));

/* Where the wide viewport left it, so crossing back restores it rather than guessing. */
let wide = true;

watch(isMobile, (mobile) => {
  if (mobile) {
    wide = isOpen.value;
    open.value = false;
  } else {
    open.value = wide;
  }
});

const state = computed<SidebarState>(() => (isOpen.value ? "expanded" : "collapsed"));
const closable = computed(() => collapses.value && (props.close || isMobile.value));
const hasHeader = computed(
  () => props.title != null || props.description != null || !!slots.actions || closable.value,
);

const theme = useResolvedTheme(
  sidebar,
  "sidebar",
  () => props,
  () => props.class as string | undefined,
);
</script>

<template>
  <aside
    data-slot="base"
    :data-state="state"
    :data-side="props.side"
    :data-variant="props.variant"
    :class="theme.class.base"
  >
    <!-- Reserves the column the fixed panel beside it occupies. -->
    <div data-slot="gap" :data-state="state" :class="theme.class.gap" />

    <div data-slot="container" :data-state="state" :class="theme.class.container">
      <div data-slot="inner" :class="theme.class.inner">
        <div v-if="hasHeader" data-slot="header" :class="theme.class.header">
          <div
            v-if="props.title != null || props.description != null"
            data-slot="wrapper"
            :class="theme.class.wrapper"
          >
            <p v-if="props.title != null" data-slot="title" :class="theme.class.title">
              {{ props.title }}
            </p>
            <p
              v-if="props.description != null"
              data-slot="description"
              :class="theme.class.description"
            >
              {{ props.description }}
            </p>
          </div>

          <div v-if="$slots.actions || closable" data-slot="actions" :class="theme.class.actions">
            <slot name="actions" />

            <button
              v-if="closable"
              type="button"
              aria-label="Collapse sidebar"
              data-slot="close"
              :class="theme.class.close"
              @click="open = false"
            >
              <component :is="props.closeIcon ?? X" />
            </button>
          </div>
        </div>

        <div data-slot="body" :class="theme.class.body">
          <slot />
        </div>

        <div v-if="$slots.footer" data-slot="footer" :class="theme.class.footer">
          <slot name="footer" />
        </div>
      </div>

      <button
        v-if="props.rail && collapses"
        type="button"
        :tabindex="-1"
        aria-label="Toggle sidebar"
        data-slot="rail"
        :data-state="state"
        :class="theme.class.rail"
        @click="open = !isOpen"
      />
    </div>
  </aside>

  <div
    v-if="props.overlay && collapses && isMobile && isOpen"
    data-slot="overlay"
    :class="theme.class.overlay"
    @click="open = false"
  />
</template>

// packages/react/src/components/Sidebar.tsx
import type React from "react";
import { useEffect, useRef, useState } from "react";
import { X } from "lucide-react";
import {
  sidebar,
  sidebarMobileQuery,
  type SidebarProps as SidebarContract,
  type SidebarState,
} from "@75neo/themes";
import { useMediaQuery } from "../hooks/useMediaQuery";
import { useResolvedTheme } from "../hooks/useResolvedTheme";

/**
 * Props for the Sidebar.
 *
 * @remarks
 * `title` is dropped from the HTML attributes, because the global attribute takes a
 * string for a tooltip where this component's heads the column.
 *
 * `children` is the body, not a trigger. A Sidebar has no trigger — it is part of the
 * page rather than something summoned onto it — so the default slot goes to the one
 * region that is always there.
 */
export interface SidebarProps
  extends Omit<React.HTMLAttributes<HTMLElement>, "title">, SidebarContract<React.ReactNode> {
  /** The scrolling middle of the column, usually a navigation. */
  children?: React.ReactNode;
  /** A row along the bottom, usually an account or a theme switch. */
  footer?: React.ReactNode;
  /** Buttons in the header, beside the close button. */
  actions?: React.ReactNode;
  /** Whether the sidebar is expanded. Leave it out to let the Sidebar keep the state. */
  open?: boolean;
  /** The starting state when the Sidebar keeps it. @defaultValue `true` */
  defaultOpen?: boolean;
  /** Fired whenever the sidebar expands or collapses, from either viewport. */
  onOpenChange?: (details: { open: boolean }) => void;
}

/**
 * A column beside the page that collapses to a strip or disappears, and slides in over
 * the page where there is no room beside it.
 *
 * @remarks
 * One state serves both viewports and the component moves it across when the viewport
 * crosses `lg`: entering the narrow one remembers where the wide one was and closes the
 * panel, and leaving it puts the remembered value back. Without that, a sidebar that is
 * expanded by design would cover a phone's content the moment the page loaded.
 *
 * The narrow panel is the same DOM as the wide column, moved. It is not a focus trap
 * and does not try to be; see the note on the recipe for why a layout element can
 * afford that and a Dialog cannot.
 */
export function Sidebar({
  ui,
  side = "start",
  variant = "sidebar",
  collapsible = "offcanvas",
  transition = true,
  title,
  description,
  close,
  closeIcon,
  rail,
  overlay = true,
  children,
  footer,
  actions,
  open,
  defaultOpen = true,
  onOpenChange,
  className,
  ...rest
}: SidebarProps) {
  const theme = useResolvedTheme(
    sidebar,
    "sidebar",
    { ui, side, variant, collapsible, transition },
    className,
  );

  const isMobile = useMediaQuery(sidebarMobileQuery);
  const [uncontrolled, setUncontrolled] = useState(defaultOpen);
  const isOpen = open ?? uncontrolled;

  const setOpen = (next: boolean) => {
    if (open === undefined) setUncontrolled(next);
    onOpenChange?.({ open: next });
  };

  /*
   * The viewport effect below has to read the state and write it, and must run only
   * when the viewport crosses — listing either as a dependency would run it on every
   * toggle instead. Both are parked in a ref by an effect declared first, so the ref is
   * already current by the time the second one reads it.
   */
  const latest = useRef({ isOpen, setOpen });
  useEffect(() => {
    latest.current = { isOpen, setOpen };
  });

  const wide = useRef(defaultOpen);
  const wasMobile = useRef<boolean | null>(null);

  useEffect(() => {
    if (wasMobile.current === isMobile) return;
    const first = wasMobile.current === null;
    wasMobile.current = isMobile;

    if (isMobile) {
      wide.current = latest.current.isOpen;
      latest.current.setOpen(false);
    } else if (!first) {
      latest.current.setOpen(wide.current);
    }
  }, [isMobile]);

  const collapses = collapsible !== "none";
  const state: SidebarState = isOpen || !collapses ? "expanded" : "collapsed";
  const closable = collapses && (close || isMobile);
  const hasHeader = title != null || description != null || actions != null || closable;

  const content = (
    <div data-slot="inner" className={theme.class.inner}>
      {hasHeader && (
        <div data-slot="header" className={theme.class.header}>
          {(title != null || description != null) && (
            <div data-slot="wrapper" className={theme.class.wrapper}>
              {title != null && (
                <p data-slot="title" className={theme.class.title}>
                  {title}
                </p>
              )}
              {description != null && (
                <p data-slot="description" className={theme.class.description}>
                  {description}
                </p>
              )}
            </div>
          )}

          {(actions != null || closable) && (
            <div data-slot="actions" className={theme.class.actions}>
              {actions}
              {closable && (
                <button
                  type="button"
                  aria-label="Collapse sidebar"
                  data-slot="close"
                  className={theme.class.close}
                  onClick={() => setOpen(false)}
                >
                  {closeIcon ?? <X />}
                </button>
              )}
            </div>
          )}
        </div>
      )}

      <div data-slot="body" className={theme.class.body}>
        {children}
      </div>

      {footer != null && (
        <div data-slot="footer" className={theme.class.footer}>
          {footer}
        </div>
      )}
    </div>
  );

  return (
    <>
      <aside
        {...rest}
        data-slot="base"
        data-state={state}
        data-side={side}
        data-variant={variant}
        className={theme.class.base}
      >
        {/* Reserves the column the fixed panel beside it occupies. */}
        <div data-slot="gap" data-state={state} className={theme.class.gap} />

        <div data-slot="container" data-state={state} className={theme.class.container}>
          {content}

          {rail && collapses && (
            <button
              type="button"
              tabIndex={-1}
              aria-label="Toggle sidebar"
              data-slot="rail"
              data-state={state}
              className={theme.class.rail}
              onClick={() => setOpen(!isOpen)}
            />
          )}
        </div>
      </aside>

      {overlay && collapses && isMobile && isOpen && (
        <div data-slot="overlay" className={theme.class.overlay} onClick={() => setOpen(false)} />
      )}
    </>
  );
}
