// packages/vue/src/components/Timer.vue
<script setup lang="ts">
import { computed } from "vue";
import { Timer as Ark } from "@ark-ui/vue/timer";
import { type TimerProps, type TimerUnit, timer } from "@75neo/themes";
import { useResolvedTheme } from "../composables/theme";

/**
 * `units` needs no `withDefaults` entry: the fallback below hands each render a fresh
 * array, so no instance shares one. `showLabels`, `controls` and `separator` default
 * on, and a type-based `defineProps` declares booleans as Boolean props, so Vue would
 * cast an absent one to `false` — leaving every timer labelless, buttonless and
 * unseparated in Vue while React worked. This is the same cast that once unticked every
 * `defaultChecked` Checkbox.
 */
const props = withDefaults(
  defineProps<
    TimerProps & {
      class?: unknown;
      ids?: { root?: string; area?: string };
    }
  >(),
  { showLabels: true, separator: ":", controls: true },
);

const emit = defineEmits<{
  /** Fired when the timer reaches its target. */
  complete: [];
  /** Fired on every tick. */
  tick: [details: { value: number }];
}>();

const theme = useResolvedTheme(
  timer,
  "timer",
  () => props,
  () => props.class as string | undefined,
);

const shown = computed<TimerUnit[]>(() => props.units ?? ["minutes", "seconds"]);

/** The buttons rendered under the digits, in order, with the text each one carries. */
const actions = [
  { action: "start", label: "Start" },
  { action: "pause", label: "Pause" },
  { action: "resume", label: "Resume" },
  { action: "reset", label: "Reset" },
] as const;
</script>

<template>
  <Ark.Root
    data-slot="base"
    :class="theme.class.base"
    :auto-start="props.autoStart"
    :countdown="props.countdown"
    :interval="props.interval"
    :start-ms="props.startMs"
    :target-ms="props.targetMs"
    :ids="props.ids"
    @complete="emit('complete')"
    @tick="emit('tick', $event)"
  >
    <Ark.Area data-slot="area" :class="theme.class.area">
      <template v-for="(unit, index) in shown" :key="unit">
        <Ark.Separator v-if="index > 0" data-slot="separator" :class="theme.class.separator">
          {{ props.separator }}
        </Ark.Separator>
        <div data-slot="itemGroup" :class="theme.class.itemGroup">
          <Ark.Item :type="unit" data-slot="item" :class="theme.class.item" />
          <span v-if="props.showLabels" data-slot="label" :class="theme.class.label">
            {{ props.labels?.[unit] ?? unit }}
          </span>
        </div>
      </template>
    </Ark.Area>

    <Ark.Control v-if="props.controls" data-slot="control" :class="theme.class.control">
      <Ark.ActionTrigger
        v-for="{ action, label } in actions"
        :key="action"
        :action="action"
        data-slot="actionTrigger"
        :class="theme.class.actionTrigger"
      >
        {{ label }}
      </Ark.ActionTrigger>
    </Ark.Control>
  </Ark.Root>
</template>

// packages/react/src/components/Timer.tsx
import { Fragment } from "react";
import type React from "react";
import { Timer as Ark, type TimerRootProps } from "@ark-ui/react/timer";
import { type TimerProps as TimerContract, type TimerUnit, timer } from "@75neo/themes";
import { useResolvedTheme } from "../hooks/useResolvedTheme";

/** The buttons rendered under the digits, in order, with the text each one carries. */
const actions = [
  { action: "start", label: "Start" },
  { action: "pause", label: "Pause" },
  { action: "resume", label: "Resume" },
  { action: "reset", label: "Reset" },
] as const;

/**
 * Props for the Timer.
 *
 * @remarks
 * Which units render is data — the `units` array from the shared contract — so the
 * digits, their labels and the separators between them all come from one list, and a
 * caller reorders the clock by reordering it.
 */
export interface TimerProps
  extends
    Omit<React.HTMLAttributes<HTMLDivElement>, "dir">,
    Pick<
      TimerRootProps,
      | "autoStart"
      | "countdown"
      | "interval"
      | "startMs"
      | "targetMs"
      | "onComplete"
      | "onTick"
      | "ids"
    >,
    TimerContract {}

export function Timer({
  ui,
  size,
  units,
  showLabels = true,
  labels,
  separator = ":",
  controls = true,
  autoStart,
  countdown,
  interval,
  startMs,
  targetMs,
  onComplete,
  onTick,
  ids,
  className,
  ...rest
}: TimerProps) {
  const theme = useResolvedTheme(timer, "timer", { ui, size }, className);

  const shown: TimerUnit[] = units ?? ["minutes", "seconds"];

  return (
    <Ark.Root
      {...rest}
      data-slot="base"
      className={theme.class.base}
      autoStart={autoStart}
      countdown={countdown}
      interval={interval}
      startMs={startMs}
      targetMs={targetMs}
      onComplete={onComplete}
      onTick={onTick}
      ids={ids}
    >
      <Ark.Area data-slot="area" className={theme.class.area}>
        {shown.map((unit, index) => (
          <Fragment key={unit}>
            {index > 0 && (
              <Ark.Separator data-slot="separator" className={theme.class.separator}>
                {separator}
              </Ark.Separator>
            )}
            <div data-slot="itemGroup" className={theme.class.itemGroup}>
              <Ark.Item type={unit} data-slot="item" className={theme.class.item} />
              {showLabels && (
                <span data-slot="label" className={theme.class.label}>
                  {labels?.[unit] ?? unit}
                </span>
              )}
            </div>
          </Fragment>
        ))}
      </Ark.Area>

      {controls && (
        <Ark.Control data-slot="control" className={theme.class.control}>
          {actions.map(({ action, label }) => (
            <Ark.ActionTrigger
              key={action}
              action={action}
              data-slot="actionTrigger"
              className={theme.class.actionTrigger}
            >
              {label}
            </Ark.ActionTrigger>
          ))}
        </Ark.Control>
      )}
    </Ark.Root>
  );
}
