// registry/react/ui/drawer/DrawerDescription.tsx
import React from "react";
import { Drawer as Ark } from "@ark-ui/react/drawer";
import { cn } from "cn";
import { drawerStyles as styles } from "@/registry/shared/lib/drawer.styles";

export interface DrawerDescriptionProps extends React.ComponentPropsWithRef<
  typeof Ark.Description
> {}

export default function DrawerDescription({
  className,
  children,
  ...props
}: DrawerDescriptionProps) {
  return (
    <Ark.Description className={cn(styles.description(), className)} {...props}>
      {children}
    </Ark.Description>
  );
}

// registry/vue/ui/drawer/DrawerDescription.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { Drawer as Ark } from "@ark-ui/vue/drawer";
import { cn } from "cn";
import { drawerStyles as styles } from "@/registry/shared/lib/drawer.styles";

interface DrawerDescriptionProps {
  class?: HTMLAttributes["class"];
}

const props = defineProps<DrawerDescriptionProps>();

defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <Ark.Description :class="cn(styles.description(), props.class)">
    <slot />
  </Ark.Description>
</template>
