// registry/react/ui/drawer/DrawerContent.tsx
import React from "react";
import { Drawer as Ark } from "@ark-ui/react/drawer";
import { cn } from "cn";
import { drawer, type DrawerSize } from "@/registry/shared/lib/drawer.styles";

export interface DrawerContentProps extends React.ComponentPropsWithRef<typeof Ark.Content> {
  size?: DrawerSize;
}

export default function DrawerContent({ size, className, children, ...props }: DrawerContentProps) {
  const styles = drawer({ size });

  return (
    <Ark.Content className={cn(styles.content(), className)} {...props}>
      {children}
    </Ark.Content>
  );
}

// registry/vue/ui/drawer/DrawerContent.vue
<script setup lang="ts">
import { computed, type HTMLAttributes } from "vue";
import { Drawer as Ark } from "@ark-ui/vue/drawer";
import { cn } from "cn";
import { drawer, type DrawerSize } from "@/registry/shared/lib/drawer.styles";

interface DrawerContentProps {
  size?: DrawerSize;
  class?: HTMLAttributes["class"];
}

const props = defineProps<DrawerContentProps>();

defineSlots<{
  default?: () => unknown;
}>();

const styles = computed(() => drawer({ size: props.size }));
</script>

<template>
  <Ark.Content :class="cn(styles.content(), props.class)">
    <slot />
  </Ark.Content>
</template>
