// packages/vue/src/password-input/password-input.vue
<script setup lang="ts">
import { type Component, computed, provide, reactive } from "vue";
import { PasswordInput as Ark } from "@ark-ui/vue/password-input";
import { Eye as EyeIcon, EyeOff as EyeOffIcon } from "@lucide/vue";
import {
  cn,
  passwordInputDefaults,
  passwordInputSizeData,
  type PasswordInputRootProps,
} from "@75neo/themes";
import { passwordInputVariantsKey } from "./variants";
import PasswordInputControl from "./control.vue";
import PasswordInputIndicator from "./indicator.vue";
import PasswordInputInput from "./input.vue";
import PasswordInputLabel from "./label.vue";
import PasswordInputVisibilityTrigger from "./visibility-trigger.vue";

const props = defineProps<
  PasswordInputRootProps<Component> & {
    class?: unknown;
    defaultVisible?: boolean;
    ids?: { input?: string; visibilityTrigger?: string };
  }
>();

const emit = defineEmits<{
  /** Fired when the secret is shown or hidden. */
  visibilityChange: [details: { visible: boolean }];
}>();

defineSlots<{
  default?: () => unknown;
}>();

/*
 * `default: undefined` keeps an absent `v-model:visible` absent. Without it the
 * declared prop would reach Ark as an explicit `false` and pin the field shut.
 */
const visible = defineModel<boolean | undefined>("visible", { default: undefined });

// Getters, so a later prop change reaches already-mounted parts.
const resolved = reactive({
  get color() {
    return props.color ?? passwordInputDefaults.color;
  },
  get size() {
    return props.size ?? passwordInputDefaults.size;
  },
});
provide(passwordInputVariantsKey, resolved);

const rootClass = computed(() =>
  cn("flex w-full min-w-0 flex-col gap-1.5", props.class as string | undefined),
);
const leadingClass = computed(() =>
  cn("shrink-0 text-dimmed [&>svg]:size-full", passwordInputSizeData.leadingIcon[resolved.size]),
);
</script>

<template>
  <Ark.Root
    data-slot="password-input"
    :class="rootClass"
    :data-color="resolved.color"
    :data-size="resolved.size"
    v-model:visible="visible"
    :default-visible="props.defaultVisible"
    :auto-complete="props.autoComplete"
    :name="props.name"
    :ignore-password-managers="props.ignorePasswordManagers"
    :disabled="props.disabled"
    :read-only="props.readOnly"
    :invalid="props.invalid"
    :required="props.required"
    :ids="props.ids"
    @visibility-change="emit('visibilityChange', $event)"
  >
    <PasswordInputLabel v-if="props.label != null">{{ props.label }}</PasswordInputLabel>
    <PasswordInputControl>
      <span
        v-if="props.leadingIcon != null"
        data-slot="password-input-leading-icon"
        :class="leadingClass"
      >
        <component :is="props.leadingIcon" />
      </span>
      <PasswordInputInput :placeholder="props.placeholder" />
      <PasswordInputVisibilityTrigger>
        <PasswordInputIndicator>
          <component :is="props.visibleIcon ?? EyeIcon" />
          <template #fallback>
            <component :is="props.hiddenIcon ?? EyeOffIcon" />
          </template>
        </PasswordInputIndicator>
      </PasswordInputVisibilityTrigger>
    </PasswordInputControl>
  </Ark.Root>
</template>

// packages/react/src/password-input/password-input.tsx
import type React from "react";
import {
  PasswordInput as Ark,
  type PasswordInputRootProps as ArkRootProps,
} from "@ark-ui/react/password-input";
import { Eye, EyeOff } from "lucide-react";
import {
  cn,
  passwordInputDefaults,
  passwordInputSizeData,
  type PasswordInputRootProps as PasswordInputContract,
} from "@75neo/themes";
import { PasswordInputVariantsContext } from "./variants";
import { PasswordInputControl } from "./control";
import { PasswordInputIndicator } from "./indicator";
import { PasswordInputInput } from "./input";
import { PasswordInputLabel } from "./label";
import { PasswordInputVisibilityTrigger } from "./visibility-trigger";

/**
 * Props for the PasswordInput.
 *
 * @remarks
 * There is no value prop, because Ark's root takes none: the field is uncontrolled
 * and both frameworks spell a controlled value too differently to share one type.
 */
export interface PasswordInputProps
  extends
    Omit<React.HTMLAttributes<HTMLDivElement>, "color" | "defaultValue" | "dir">,
    Pick<ArkRootProps, "visible" | "defaultVisible" | "onVisibilityChange" | "ids">,
    PasswordInputContract<React.ReactNode> {}

export function PasswordInput({
  color,
  size,
  label,
  placeholder,
  autoComplete,
  name,
  ignorePasswordManagers,
  disabled,
  readOnly,
  invalid,
  required,
  leadingIcon,
  visibleIcon,
  hiddenIcon,
  visible,
  defaultVisible,
  onVisibilityChange,
  ids,
  className,
  ...rest
}: PasswordInputProps) {
  const resolved = {
    color: color ?? passwordInputDefaults.color,
    size: size ?? passwordInputDefaults.size,
  };

  return (
    <PasswordInputVariantsContext.Provider value={resolved}>
      <Ark.Root
        {...rest}
        data-slot="password-input"
        data-color={resolved.color}
        data-size={resolved.size}
        className={cn("flex w-full min-w-0 flex-col gap-1.5", className)}
        visible={visible}
        defaultVisible={defaultVisible}
        onVisibilityChange={onVisibilityChange}
        autoComplete={autoComplete}
        name={name}
        ignorePasswordManagers={ignorePasswordManagers}
        disabled={disabled}
        readOnly={readOnly}
        invalid={invalid}
        required={required}
        ids={ids}
      >
        {label != null && <PasswordInputLabel>{label}</PasswordInputLabel>}
        <PasswordInputControl>
          {leadingIcon != null && (
            <span
              data-slot="password-input-leading-icon"
              className={cn(
                "shrink-0 text-dimmed [&>svg]:size-full",
                passwordInputSizeData.leadingIcon[resolved.size],
              )}
            >
              {leadingIcon}
            </span>
          )}
          <PasswordInputInput placeholder={placeholder} />
          <PasswordInputVisibilityTrigger>
            <PasswordInputIndicator fallback={hiddenIcon ?? <EyeOff />}>
              {visibleIcon ?? <Eye />}
            </PasswordInputIndicator>
          </PasswordInputVisibilityTrigger>
        </PasswordInputControl>
      </Ark.Root>
    </PasswordInputVariantsContext.Provider>
  );
}
