// registry/react/ui/number-input/NumberInputIncrementTrigger.tsx
import React from "react";
import { NumberInput as Ark } from "@ark-ui/react/number-input";
import { cn } from "cn";
import { numberInputStyles as styles } from "@/registry/shared/lib/number-input.styles";

export interface NumberInputIncrementTriggerProps extends React.ComponentPropsWithRef<
  typeof Ark.IncrementTrigger
> {}

export default function NumberInputIncrementTrigger({
  className,
  children,
  ...props
}: NumberInputIncrementTriggerProps) {
  return (
    <Ark.IncrementTrigger className={cn(styles.incrementTrigger(), className)} {...props}>
      {children}
    </Ark.IncrementTrigger>
  );
}

// registry/vue/ui/number-input/NumberInputIncrementTrigger.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { NumberInput as Ark } from "@ark-ui/vue/number-input";
import { cn } from "cn";
import { numberInputStyles as styles } from "@/registry/shared/lib/number-input.styles";

interface NumberInputIncrementTriggerProps {
  class?: HTMLAttributes["class"];
}

const props = defineProps<NumberInputIncrementTriggerProps>();

defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <Ark.IncrementTrigger :class="cn(styles.incrementTrigger(), props.class)">
    <slot />
  </Ark.IncrementTrigger>
</template>
