// registry/react/ui/toc/TocItem.tsx
import React from "react";
import { Toc as Ark } from "@ark-ui/react/toc";
import { cn } from "cn";
import { tocStyles as styles } from "@/registry/shared/lib/toc.styles";

export interface TocItemProps extends React.ComponentPropsWithRef<typeof Ark.Item> {}

export default function TocItem({ className, children, ...props }: TocItemProps) {
  return (
    <Ark.Item className={cn(styles.item(), className)} {...props}>
      {children}
    </Ark.Item>
  );
}

// registry/vue/ui/toc/TocItem.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { Toc as Ark, type TocItemData } from "@ark-ui/vue/toc";
import { cn } from "cn";
import { tocStyles as styles } from "@/registry/shared/lib/toc.styles";

interface TocItemProps {
  item: TocItemData;
  class?: HTMLAttributes["class"];
}

const props = defineProps<TocItemProps>();

defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <Ark.Item :item="props.item" :class="cn(styles.item(), props.class)">
    <slot />
  </Ark.Item>
</template>
