// registry/react/ui/toc/TocIndicator.tsx
import React from "react";
import { Toc as Ark } from "@ark-ui/react/toc";
import { cn } from "cn";
import { tocStyles as styles } from "@/registry/shared/lib/toc.styles";

export interface TocIndicatorProps extends React.ComponentPropsWithRef<"li"> {}

export default function TocIndicator({ className, ...props }: TocIndicatorProps) {
  return (
    <Ark.Indicator asChild>
      <li aria-hidden className={cn(styles.indicator(), className)} {...props} />
    </Ark.Indicator>
  );
}

// registry/vue/ui/toc/TocIndicator.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { Toc as Ark } from "@ark-ui/vue/toc";
import { cn } from "cn";
import { tocStyles as styles } from "@/registry/shared/lib/toc.styles";

interface TocIndicatorProps {
  class?: HTMLAttributes["class"];
}

const props = defineProps<TocIndicatorProps>();
</script>

<template>
  <Ark.Indicator as-child>
    <li aria-hidden="true" :class="cn(styles.indicator(), props.class)" />
  </Ark.Indicator>
</template>
