// registry/react/ui/rating-group/RatingGroupLabel.tsx
import React from "react";
import { RatingGroup as Ark } from "@ark-ui/react/rating-group";
import { cn } from "cn";
import { ratingGroupStyles as styles } from "@/registry/shared/lib/rating-group.styles";

export interface RatingGroupLabelProps extends React.ComponentPropsWithRef<typeof Ark.Label> {}

export default function RatingGroupLabel({ className, children, ...props }: RatingGroupLabelProps) {
  return (
    <Ark.Label className={cn(styles.label(), className)} {...props}>
      {children}
    </Ark.Label>
  );
}

// registry/vue/ui/rating-group/RatingGroupLabel.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { RatingGroup as Ark } from "@ark-ui/vue/rating-group";
import { cn } from "cn";
import { ratingGroupStyles as styles } from "@/registry/shared/lib/rating-group.styles";

interface RatingGroupLabelProps {
  class?: HTMLAttributes["class"];
}

const props = defineProps<RatingGroupLabelProps>();

defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <Ark.Label :class="cn(styles.label(), props.class)">
    <slot />
  </Ark.Label>
</template>
