// registry/react/ui/radio-group/RadioGroupItemControl.tsx
import React from "react";
import { RadioGroup as Ark } from "@ark-ui/react/radio-group";
import { cn } from "cn";
import { radioGroupStyles as styles } from "@/registry/shared/lib/radio-group.styles";

export interface RadioGroupItemControlProps extends React.ComponentPropsWithRef<
  typeof Ark.ItemControl
> {}

export default function RadioGroupItemControl({ className, ...props }: RadioGroupItemControlProps) {
  return <Ark.ItemControl className={cn(styles.itemControl(), className)} {...props} />;
}

// registry/vue/ui/radio-group/RadioGroupItemControl.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { RadioGroup as Ark } from "@ark-ui/vue/radio-group";
import { cn } from "cn";
import { radioGroupStyles as styles } from "@/registry/shared/lib/radio-group.styles";

interface RadioGroupItemControlProps {
  class?: HTMLAttributes["class"];
}

const props = defineProps<RadioGroupItemControlProps>();
</script>

<template>
  <Ark.ItemControl :class="cn(styles.itemControl(), props.class)" />
</template>
