// registry/vue/ui/radio-group/RadioGroupItem.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { RadioGroup as Ark } from "@ark-ui/vue/radio-group";
import { cn } from "cn";
import { radioGroupStyles as styles } from "@/registry/shared/lib/radio-group.styles";

interface RadioGroupItemProps {
  value: string;
  disabled?: boolean;
  invalid?: boolean;
  class?: HTMLAttributes["class"];
}

const props = withDefaults(defineProps<RadioGroupItemProps>(), {
  disabled: undefined,
  invalid: undefined,
});

defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <Ark.Item
    :value="props.value"
    :disabled="props.disabled"
    :invalid="props.invalid"
    :class="cn(styles.item(), props.class)"
  >
    <slot />
  </Ark.Item>
</template>

// registry/react/ui/radio-group/RadioGroupItem.tsx
import React from "react";
import { RadioGroup as Ark } from "@ark-ui/react/radio-group";
import { cn } from "cn";
import { radioGroupStyles as styles } from "@/registry/shared/lib/radio-group.styles";

export interface RadioGroupItemProps extends React.ComponentPropsWithRef<typeof Ark.Item> {}

export default function RadioGroupItem({ className, children, ...props }: RadioGroupItemProps) {
  return (
    <Ark.Item className={cn(styles.item(), className)} {...props}>
      {children}
    </Ark.Item>
  );
}
