// registry/vue/ui/slider/SliderThumb.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { Slider as Ark } from "@ark-ui/vue/slider";
import { cn } from "cn";
import { sliderStyles as styles } from "@/registry/shared/lib/slider.styles";

interface SliderThumbProps {
  index: number;
  class?: HTMLAttributes["class"];
}

const props = defineProps<SliderThumbProps>();

defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <Ark.Thumb :index="props.index" :class="cn(styles.thumb(), props.class)">
    <slot />
  </Ark.Thumb>
</template>

// registry/react/ui/slider/SliderThumb.tsx
import React from "react";
import { Slider as Ark } from "@ark-ui/react/slider";
import { cn } from "cn";
import { sliderStyles as styles } from "@/registry/shared/lib/slider.styles";

export interface SliderThumbProps extends React.ComponentPropsWithRef<typeof Ark.Thumb> {}

export default function SliderThumb({ className, children, ...props }: SliderThumbProps) {
  return (
    <Ark.Thumb className={cn(styles.thumb(), className)} {...props}>
      {children}
    </Ark.Thumb>
  );
}
