// apps/playground/src/previews/SegmentGroupPreview.tsx
import type { ReactNode } from "react";
import { SegmentGroup } from "@75neo/react/segment-group";
import { segmentGroupSchema } from "@75neo/themes";

const sizes = segmentGroupSchema.size.values;
const colors = segmentGroupSchema.color.values;

const items = [
  { value: "day", label: "Day" },
  { value: "week", label: "Week" },
  { value: "month", label: "Month" },
];

const row = "grid gap-2 @sm:grid-cols-[4.5rem_minmax(0,1fr)] @sm:gap-4";
const rowLabel = "text-dimmed font-mono text-[0.6875rem] leading-none @sm:pt-3";
const rowItems = "min-w-0 max-w-xs";
const group = "flex flex-col gap-5";
const rule = "border-muted my-6";

function Row({ label, children }: { label: string; children: ReactNode }) {
  return (
    <div className={row}>
      <p className={rowLabel} data-identifier>
        {label}
      </p>
      <div className={rowItems}>{children}</div>
    </div>
  );
}

export default function SegmentGroupPreview() {
  return (
    <div className="@container">
      <div className={group}>
        {sizes.map((size) => (
          <Row key={size} label={size}>
            <SegmentGroup size={size} items={items} defaultValue="week" />
          </Row>
        ))}
      </div>

      <hr className={rule} />

      <div className={group}>
        <Row label="colors">
          <div className="flex flex-col items-start gap-2">
            {colors.map((color) => (
              <SegmentGroup key={color} color={color} items={items} defaultValue="week" />
            ))}
          </div>
        </Row>

        <Row label="vertical">
          <SegmentGroup items={items} orientation="vertical" defaultValue="week" />
        </Row>

        <Row label="disabled">
          <SegmentGroup items={items} disabled />
        </Row>
      </div>
    </div>
  );
}

// apps/playground/src/previews/SegmentGroupPreview.vue
<script setup lang="ts">
import { SegmentGroup } from "@75neo/vue/segment-group";
import { segmentGroupSchema } from "@75neo/themes";

const sizes = segmentGroupSchema.size.values;
const colors = segmentGroupSchema.color.values;

const items = [
  { value: "day", label: "Day" },
  { value: "week", label: "Week" },
  { value: "month", label: "Month" },
];

const row = "grid gap-2 @sm:grid-cols-[4.5rem_minmax(0,1fr)] @sm:gap-4";
const rowLabel = "text-dimmed font-mono text-[0.6875rem] leading-none @sm:pt-3";
const rowItems = "min-w-0 max-w-xs";
const group = "flex flex-col gap-5";
const rule = "border-muted my-6";
</script>

<template>
  <div class="@container">
    <div :class="group">
      <div v-for="size in sizes" :key="size" :class="row">
        <p :class="rowLabel" data-identifier>{{ size }}</p>
        <div :class="rowItems">
          <SegmentGroup :size="size" :items="items" default-value="week" />
        </div>
      </div>
    </div>

    <hr :class="rule" />

    <div :class="group">
      <div :class="row">
        <p :class="rowLabel" data-identifier>colors</p>
        <div :class="[rowItems, 'flex flex-col items-start gap-2']">
          <SegmentGroup
            v-for="color in colors"
            :key="color"
            :color="color"
            :items="items"
            default-value="week"
          />
        </div>
      </div>

      <div :class="row">
        <p :class="rowLabel" data-identifier>vertical</p>
        <div :class="rowItems">
          <SegmentGroup :items="items" orientation="vertical" default-value="week" />
        </div>
      </div>

      <div :class="row">
        <p :class="rowLabel" data-identifier>disabled</p>
        <div :class="rowItems">
          <SegmentGroup :items="items" disabled />
        </div>
      </div>
    </div>
  </div>
</template>
