// packages/vue/src/hover-card/hover-card.vue
<script setup lang="ts">
import { type Component, provide, reactive } from "vue";
import { HoverCard as Ark } from "@ark-ui/vue/hover-card";
import { hoverCardDefaults, type HoverCardRootProps } from "@75neo/themes";
import { hoverCardVariantsKey } from "./variants";
import HoverCardArrow from "./arrow.vue";
import HoverCardBody from "./body.vue";
import HoverCardContent from "./content.vue";
import HoverCardDescription from "./description.vue";
import HoverCardTitle from "./title.vue";

const props = withDefaults(
  defineProps<
    HoverCardRootProps<Component> & {
      class?: unknown;
    }
  >(),
  { arrow: false, placement: "bottom", offset: 8 },
);

const emit = defineEmits<{
  /** Fired when the card opens or closes. */
  openChange: [details: { open: boolean }];
}>();

defineSlots<{
  /** The element the card appears beside. It becomes the trigger. */
  default?: () => unknown;
}>();

/*
 * `default: undefined` keeps an absent `v-model:open` absent. Without it the declared
 * prop would reach Ark as an explicit `false` and pin the card shut, which would
 * leave `defaultOpen` with nothing to do.
 */
const open = defineModel<boolean | undefined>("open", { default: undefined });

// Getters, so a later prop change reaches already-mounted parts.
const resolved = reactive({
  get size() {
    return props.size ?? hoverCardDefaults.size;
  },
});
provide(hoverCardVariantsKey, resolved);
</script>

<template>
  <Ark.Root
    data-slot="hover-card"
    :data-size="resolved.size"
    v-model:open="open"
    @open-change="emit('openChange', $event)"
    :open-delay="props.openDelay"
    :close-delay="props.closeDelay"
    :disabled="props.disabled"
    :positioning="{ placement: props.placement, offset: { mainAxis: props.offset } }"
    :lazy-mount="props.lazyMount"
    :unmount-on-exit="props.unmountOnExit"
  >
    <Ark.Trigger v-if="$slots.default" as-child>
      <slot />
    </Ark.Trigger>
    <HoverCardContent :portal="props.portal" :class="props.class as string | undefined">
      <HoverCardArrow v-if="props.arrow" />
      <HoverCardTitle v-if="props.title != null">{{ props.title }}</HoverCardTitle>
      <HoverCardDescription v-if="props.description != null">
        {{ props.description }}
      </HoverCardDescription>
      <HoverCardBody v-if="props.body != null">
        <component :is="props.body" />
      </HoverCardBody>
    </HoverCardContent>
  </Ark.Root>
</template>

// packages/react/src/hover-card/hover-card.tsx
import type React from "react";
import { HoverCard as Ark } from "@ark-ui/react/hover-card";
import { hoverCardDefaults, type HoverCardRootProps as HoverCardContract } from "@75neo/themes";
import { HoverCardVariantsContext } from "./variants";
import { HoverCardArrow } from "./arrow";
import { HoverCardBody } from "./body";
import { HoverCardContent } from "./content";
import { HoverCardDescription } from "./description";
import { HoverCardTitle } from "./title";

/**
 * Props for the HoverCard.
 *
 * @remarks
 * `title` is dropped from the HTML attributes, because the global attribute is the
 * wrong kind of title, and so is `content`. `dir` belongs to the locale provider.
 *
 * The open state comes from Ark, because React and Vue spell a controlled value too
 * differently to share one type.
 *
 * `children` is the trigger, not the body: the body is data, and the one element a
 * caller has to own is what the card appears beside.
 */
export interface HoverCardProps
  extends
    Omit<React.HTMLAttributes<HTMLDivElement>, "title" | "dir" | "content">,
    Pick<React.ComponentProps<typeof Ark.Root>, "open" | "defaultOpen" | "onOpenChange" | "ids">,
    HoverCardContract<React.ReactNode> {
  /** The element the card appears beside. It becomes the trigger. */
  children?: React.ReactNode;
}

export function HoverCard({
  size,
  title,
  description,
  body,
  arrow = false,
  placement = "bottom",
  offset = 8,
  openDelay,
  closeDelay,
  disabled,
  portal,
  lazyMount,
  unmountOnExit,
  children,
  open,
  defaultOpen,
  onOpenChange,
  ids,
  className,
  ...rest
}: HoverCardProps) {
  const resolved = { size: size ?? hoverCardDefaults.size };

  return (
    <HoverCardVariantsContext.Provider value={resolved}>
      <Ark.Root
        {...rest}
        open={open}
        defaultOpen={defaultOpen}
        onOpenChange={onOpenChange}
        openDelay={openDelay}
        closeDelay={closeDelay}
        disabled={disabled}
        positioning={{ placement, offset: { mainAxis: offset } }}
        lazyMount={lazyMount}
        unmountOnExit={unmountOnExit}
        ids={ids}
        data-slot="hover-card"
        data-size={resolved.size}
      >
        {children != null && <Ark.Trigger asChild>{children}</Ark.Trigger>}
        <HoverCardContent portal={portal} className={className}>
          {arrow && <HoverCardArrow />}
          {title != null && <HoverCardTitle>{title}</HoverCardTitle>}
          {description != null && <HoverCardDescription>{description}</HoverCardDescription>}
          {body != null && <HoverCardBody>{body}</HoverCardBody>}
        </HoverCardContent>
      </Ark.Root>
    </HoverCardVariantsContext.Provider>
  );
}
