// packages/react/src/components/Listbox.tsx
import type React from "react";
import { useMemo } from "react";
import { Listbox as Ark, createListCollection, type ListboxRootProps } from "@ark-ui/react/listbox";
import { Check } from "lucide-react";
import { listbox, type ListboxItem, type ListboxProps as ListboxContract } from "@75neo/themes";
import { useResolvedTheme } from "../hooks/useResolvedTheme";

/** The item shape this adapter builds its collection from. */
type Item = ListboxItem<React.ReactNode>;

/**
 * Props for the Listbox.
 *
 * @remarks
 * `color` is dropped from the HTML attributes, because the legacy presentational
 * attribute would collide with the variant of the same name. `defaultValue` goes with
 * it, since the attribute admits a string where Ark's root takes an array of them,
 * and `onSelect` because Ark's is called with a selection rather than with a DOM
 * event.
 *
 * The selection props come from Ark, because React and Vue spell a controlled value
 * too differently to share one type.
 */
export interface ListboxProps
  extends
    Omit<React.HTMLAttributes<HTMLDivElement>, "color" | "defaultValue" | "dir" | "onSelect">,
    Pick<
      ListboxRootProps<Item>,
      "value" | "defaultValue" | "onValueChange" | "onHighlightChange" | "onSelect" | "ids"
    >,
    ListboxContract<React.ReactNode> {}

export function Listbox({
  ui,
  color,
  size,
  items,
  label,
  emptyMessage,
  selectionMode,
  deselectable,
  loopFocus,
  disabled,
  selectedIcon,
  value,
  defaultValue,
  onValueChange,
  onHighlightChange,
  onSelect,
  ids,
  className,
  ...rest
}: ListboxProps) {
  const theme = useResolvedTheme(listbox, "listbox", { ui, color, size }, className);

  /*
   * The item shape is exactly what Ark's collection reads by default — `value`,
   * `label` and `disabled` — so no accessors are passed. Rebuilt whenever the options
   * change, which keeps a changed `items` prop honest.
   */
  const collection = useMemo(() => createListCollection({ items }), [items]);

  return (
    <Ark.Root
      {...rest}
      collection={collection}
      data-slot="base"
      className={theme.class.base}
      value={value}
      defaultValue={defaultValue}
      onValueChange={onValueChange}
      onHighlightChange={onHighlightChange}
      onSelect={onSelect}
      selectionMode={selectionMode}
      deselectable={deselectable}
      loopFocus={loopFocus}
      disabled={disabled}
      ids={ids}
    >
      {label != null && (
        <Ark.Label data-slot="label" className={theme.class.label}>
          {label}
        </Ark.Label>
      )}

      <Ark.Content data-slot="content" className={theme.class.content}>
        {/* Ark renders this only while the collection is empty, so the message and the
            rows never appear together. */}
        <Ark.Empty data-slot="empty" className={theme.class.empty}>
          {emptyMessage ?? "No options."}
        </Ark.Empty>

        {collection.items.map((item) => (
          <Ark.Item key={item.value} item={item} data-slot="item" className={theme.class.item}>
            {item.icon != null && (
              <span data-slot="leadingIcon" className={theme.class.leadingIcon}>
                {item.icon}
              </span>
            )}
            <Ark.ItemText data-slot="itemText" className={theme.class.itemText}>
              {item.label}
            </Ark.ItemText>
            <Ark.ItemIndicator data-slot="itemIndicator" className={theme.class.itemIndicator}>
              {selectedIcon ?? <Check />}
            </Ark.ItemIndicator>
          </Ark.Item>
        ))}
      </Ark.Content>
    </Ark.Root>
  );
}

// packages/vue/src/components/Listbox.vue
<script setup lang="ts">
import { type Component, computed } from "vue";
import {
  Listbox as Ark,
  createListCollection,
  type ListboxHighlightChangeDetails,
  type ListboxSelectionDetails,
  type ListboxValueChangeDetails,
} from "@ark-ui/vue/listbox";
import { Check } from "@lucide/vue";
import { listbox, type ListboxItem, type ListboxProps } from "@75neo/themes";
import { useResolvedTheme } from "../composables/theme";

/**
 * The selection lives outside the shared contract, because React and Vue spell a
 * controlled value too differently to share one type. Here it is `v-model`, holding
 * an array of item values whatever the selection mode.
 */
const props = withDefaults(
  defineProps<
    ListboxProps<Component> & {
      defaultValue?: string[];
      class?: unknown;
      ids?: { root?: string; content?: string; label?: string };
    }
  >(),
  /*
   * Named so Ark receives a real value rather than an `undefined` spread over its
   * own default. Every other boolean here defaults to off, which is what Vue's
   * Boolean casting produces anyway.
   */
  { selectionMode: "single" },
);

const emit = defineEmits<{
  /** Fired when the selection changes. */
  valueChange: [details: ListboxValueChangeDetails<ListboxItem<Component>>];
  /** Fired when the highlighted option changes. */
  highlightChange: [details: ListboxHighlightChangeDetails<ListboxItem<Component>>];
  /** Fired when an option is chosen. */
  select: [details: ListboxSelectionDetails];
}>();

defineSlots<{
  /** Replaces the caption above the list. Falls back to `label`. */
  label?: () => unknown;
  /** Replaces an option's text with arbitrary markup. Falls back to `item.label`. */
  item?: (props: { item: ListboxItem<Component> }) => unknown;
  /** Replaces the message shown when there are no options. Falls back to `emptyMessage`. */
  empty?: () => unknown;
}>();

/*
 * `default: undefined` keeps an absent `v-model` absent. Without it the declared prop
 * would reach Ark as a value and pin the list to a controlled selection, which
 * would leave `defaultValue` with nothing to do.
 */
const value = defineModel<string[] | undefined>({ default: undefined });

/*
 * The item shape is exactly what Ark's collection reads by default — `value`,
 * `label` and `disabled` — so no accessors are passed. Rebuilt whenever the options
 * change, which keeps a changed `items` prop honest.
 */
const collection = computed(() => createListCollection({ items: props.items }));

const theme = useResolvedTheme(
  listbox,
  "listbox",
  () => props,
  () => props.class as string | undefined,
);
</script>

<template>
  <Ark.Root
    v-model="value"
    :collection="collection"
    data-slot="base"
    :class="theme.class.base"
    :default-value="props.defaultValue"
    :selection-mode="props.selectionMode"
    :deselectable="props.deselectable"
    :loop-focus="props.loopFocus"
    :disabled="props.disabled"
    :ids="props.ids"
    @value-change="emit('valueChange', $event)"
    @highlight-change="emit('highlightChange', $event)"
    @select="emit('select', $event)"
  >
    <Ark.Label
      v-if="props.label != null || $slots.label"
      data-slot="label"
      :class="theme.class.label"
    >
      <slot name="label">{{ props.label }}</slot>
    </Ark.Label>

    <Ark.Content data-slot="content" :class="theme.class.content">
      <!--
        Ark renders this only while the collection is empty, so the message and the
        rows never appear together.
      -->
      <Ark.Empty data-slot="empty" :class="theme.class.empty">
        <slot name="empty">{{ props.emptyMessage ?? "No options." }}</slot>
      </Ark.Empty>

      <Ark.Item
        v-for="item in collection.items"
        :key="item.value"
        :item="item"
        data-slot="item"
        :class="theme.class.item"
      >
        <span v-if="item.icon" data-slot="leadingIcon" :class="theme.class.leadingIcon">
          <component :is="item.icon" />
        </span>
        <Ark.ItemText data-slot="itemText" :class="theme.class.itemText">
          <slot name="item" :item="item">{{ item.label }}</slot>
        </Ark.ItemText>
        <Ark.ItemIndicator data-slot="itemIndicator" :class="theme.class.itemIndicator">
          <component :is="props.selectedIcon ?? Check" />
        </Ark.ItemIndicator>
      </Ark.Item>
    </Ark.Content>
  </Ark.Root>
</template>
