// packages/react/src/components/Toast.tsx
import type React from "react";
import {
  Toaster as ArkToaster,
  Toast as ArkToast,
  type CreateToasterReturn,
} from "@ark-ui/react/toast";
import { Portal } from "@ark-ui/react/portal";
import { CircleAlert, CircleCheck, Info, LoaderCircle, TriangleAlert, X } from "lucide-react";
import { toast, type ToastProps as ToastContract, type ToastType } from "@75neo/themes";
import { useResolvedTheme } from "../hooks/useResolvedTheme";

const defaultIcons: Record<ToastType, React.ReactNode> = {
  success: <CircleCheck />,
  error: <CircleAlert />,
  warning: <TriangleAlert />,
  info: <Info />,
  loading: <LoaderCircle />,
};

/**
 * Props for the Toast region.
 */
export interface ToastProps
  extends
    Omit<React.HTMLAttributes<HTMLDivElement>, "dir" | "color">,
    ToastContract<React.ReactNode> {
  /** The toast store driving this region, created with `createToaster`. */
  toaster: CreateToasterReturn<any>;
}

export function Toast({
  ui,
  color,
  size,
  placement,
  closeIcon,
  icons,
  portal = true,
  toaster,
  className,
  ...rest
}: ToastProps) {
  const theme = useResolvedTheme(toast, "toast", { ui, color, size, placement }, className);

  const content = (
    <ArkToaster toaster={toaster} data-slot="group" className={theme.class.group} {...rest}>
      {(t) => {
        const type = t.type as ToastType | undefined;
        const icon = (type && (icons?.[type] ?? defaultIcons[type])) ?? null;

        return (
          <ArkToast.Root key={t.id} data-slot="base" className={theme.class.base}>
            {(t.title != null || icon != null) && (
              <ArkToast.Title data-slot="title" className={theme.class.title}>
                {icon && (
                  <span data-slot="leadingIcon" className={theme.class.leadingIcon}>
                    {icon}
                  </span>
                )}
                {t.title}
              </ArkToast.Title>
            )}
            {t.description != null && (
              <ArkToast.Description data-slot="description" className={theme.class.description}>
                {t.description}
              </ArkToast.Description>
            )}
            {t.action && (
              <ArkToast.ActionTrigger
                data-slot="actionTrigger"
                className={theme.class.actionTrigger}
              >
                {t.action.label}
              </ArkToast.ActionTrigger>
            )}
            {t.closable !== false && (
              <ArkToast.CloseTrigger
                data-slot="closeTrigger"
                className={theme.class.closeTrigger}
                aria-label="Close"
              >
                {closeIcon ?? <X />}
              </ArkToast.CloseTrigger>
            )}
          </ArkToast.Root>
        );
      }}
    </ArkToaster>
  );

  return portal ? <Portal>{content}</Portal> : content;
}

// packages/vue/src/components/Toast.vue
<script setup lang="ts">
import { type Component, onMounted, ref } from "vue";
import {
  Toaster as ArkToaster,
  Toast as ArkToast,
  type CreateToasterReturn,
} from "@ark-ui/vue/toast";
import { CircleAlert, CircleCheck, Info, LoaderCircle, TriangleAlert, X } from "@lucide/vue";
import { toast, type ToastProps, type ToastType } from "@75neo/themes";
import { useResolvedTheme } from "../composables/theme";

const defaultIcons: Record<ToastType, Component> = {
  success: CircleCheck,
  error: CircleAlert,
  warning: TriangleAlert,
  info: Info,
  loading: LoaderCircle,
};

const props = withDefaults(
  defineProps<
    ToastProps<Component> & {
      toaster: CreateToasterReturn<any>;
      class?: unknown;
    }
  >(),
  {
    portal: true,
  },
);

const mounted = ref(false);
onMounted(() => {
  mounted.value = true;
});

function resolveIcon(type?: string): Component | undefined {
  if (!type) return undefined;
  const t = type as ToastType;
  return props.icons?.[t] ?? defaultIcons[t];
}

const theme = useResolvedTheme(
  toast,
  "toast",
  () => props,
  () => props.class as string | undefined,
);
</script>

<template>
  <Teleport to="body" :disabled="!props.portal || !mounted">
    <ArkToaster :toaster="props.toaster" data-slot="group" :class="theme.class.group">
      <template #default="t">
        <ArkToast.Root :key="t.id" data-slot="base" :class="theme.class.base">
          <ArkToast.Title
            v-if="t.title != null || resolveIcon(t.type)"
            data-slot="title"
            :class="theme.class.title"
          >
            <span
              v-if="resolveIcon(t.type)"
              data-slot="leadingIcon"
              :class="theme.class.leadingIcon"
            >
              <component :is="resolveIcon(t.type)" />
            </span>
            <component :is="t.title" v-if="typeof t.title === 'object'" />
            <template v-else>{{ t.title }}</template>
          </ArkToast.Title>
          <ArkToast.Description
            v-if="t.description != null"
            data-slot="description"
            :class="theme.class.description"
          >
            <component :is="t.description" v-if="typeof t.description === 'object'" />
            <template v-else>{{ t.description }}</template>
          </ArkToast.Description>
          <ArkToast.ActionTrigger
            v-if="t.action"
            data-slot="actionTrigger"
            :class="theme.class.actionTrigger"
          >
            {{ t.action.label }}
          </ArkToast.ActionTrigger>
          <ArkToast.CloseTrigger
            v-if="t.closable !== false"
            data-slot="closeTrigger"
            :class="theme.class.closeTrigger"
            aria-label="Close"
          >
            <component :is="props.closeIcon ?? X" />
          </ArkToast.CloseTrigger>
        </ArkToast.Root>
      </template>
    </ArkToaster>
  </Teleport>
</template>
