// registry/vue/ui/progress/ProgressLabel.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { Progress as Ark } from "@ark-ui/vue/progress";
import { cn } from "cn";
import { progressStyles as styles } from "@/registry/shared/lib/progress.styles";

interface ProgressLabelProps {
  class?: HTMLAttributes["class"];
}

const props = defineProps<ProgressLabelProps>();

defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <Ark.Label :class="cn(styles.label(), props.class)">
    <slot />
  </Ark.Label>
</template>

// registry/react/ui/progress/ProgressLabel.tsx
import React from "react";
import { Progress as Ark } from "@ark-ui/react/progress";
import { cn } from "cn";
import { progressStyles as styles } from "@/registry/shared/lib/progress.styles";

export interface ProgressLabelProps extends React.ComponentPropsWithRef<typeof Ark.Label> {}

export default function ProgressLabel({ className, children, ...props }: ProgressLabelProps) {
  return (
    <Ark.Label className={cn(styles.label(), className)} {...props}>
      {children}
    </Ark.Label>
  );
}
