// registry/vue/ui/progress/ProgressValueText.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { Progress as Ark } from "@ark-ui/vue/progress";
import { cn } from "cn";
import { progress } from "@/registry/shared/lib/progress.styles";

interface ProgressValueTextProps {
  class?: HTMLAttributes["class"];
}

const props = defineProps<ProgressValueTextProps>();

const styles = progress();
</script>

<template>
  <Ark.ValueText :class="cn(styles.valueText(), props.class)" />
</template>

// registry/react/ui/progress/ProgressValueText.tsx
import React from "react";
import { Progress as Ark } from "@ark-ui/react/progress";
import { cn } from "cn";
import { progress } from "@/registry/shared/lib/progress.styles";

export interface ProgressValueTextProps extends React.ComponentPropsWithRef<typeof Ark.ValueText> {}

export default function ProgressValueText({
  className,
  children,
  ...props
}: ProgressValueTextProps) {
  const styles = progress();

  return (
    <Ark.ValueText className={cn(styles.valueText(), className)} {...props}>
      {children}
    </Ark.ValueText>
  );
}
