// registry/vue/ui/progress/Progress.vue
<script setup lang="ts">
import { computed, type HTMLAttributes } from "vue";
import { Progress as Ark } from "@ark-ui/vue/progress";
import { cn } from "cn";
import { progress, type ProgressSize, type Intent } from "@/registry/shared/lib/progress.styles";

interface ProgressProps {
  defaultValue?: number | null;
  min?: number;
  max?: number;
  orientation?: "horizontal" | "vertical";
  locale?: string;
  formatOptions?: Intl.NumberFormatOptions;
  size?: ProgressSize;
  color?: Intent;
  class?: HTMLAttributes["class"];
}

const props = withDefaults(defineProps<ProgressProps>(), {
  size: "md",
});

const value = defineModel<number | null>();

defineSlots<{
  default?: () => unknown;
}>();

const styles = computed(() => progress({ color: props.color }));
</script>

<template>
  <Ark.Root
    v-model="value"
    :default-value="props.defaultValue"
    :min="props.min"
    :max="props.max"
    :orientation="props.orientation"
    :locale="props.locale"
    :format-options="props.formatOptions"
    :data-size="props.size"
    :class="cn(styles.root(), props.class)"
  >
    <slot />
  </Ark.Root>
</template>

// registry/react/ui/progress/Progress.tsx
import React from "react";
import { Progress as Ark } from "@ark-ui/react/progress";
import { cn } from "cn";
import { progress, type ProgressSize, type Intent } from "@/registry/shared/lib/progress.styles";

export interface ProgressProps extends Omit<React.ComponentPropsWithRef<typeof Ark.Root>, "color"> {
  color?: Intent;
  size?: ProgressSize;
}

export default function Progress({
  color,
  size = "md",
  className,
  children,
  ...props
}: ProgressProps) {
  const styles = progress({ color });

  return (
    <Ark.Root className={cn(styles.root(), className)} data-size={size} {...props}>
      {children}
    </Ark.Root>
  );
}
