// registry/vue/ui/fieldset/FieldsetHelperText.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { Fieldset as Ark } from "@ark-ui/vue/fieldset";
import { cn } from "cn";
import { fieldsetStyles as styles } from "@/registry/shared/lib/fieldset.styles";

interface FieldsetHelperTextProps {
  class?: HTMLAttributes["class"];
}

const props = defineProps<FieldsetHelperTextProps>();

defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <Ark.HelperText :class="cn(styles.helperText(), props.class)">
    <slot />
  </Ark.HelperText>
</template>

// registry/react/ui/fieldset/FieldsetHelperText.tsx
import React from "react";
import { Fieldset as Ark } from "@ark-ui/react/fieldset";
import { cn } from "cn";
import { fieldsetStyles as styles } from "@/registry/shared/lib/fieldset.styles";

export interface FieldsetHelperTextProps extends React.ComponentPropsWithRef<
  typeof Ark.HelperText
> {}

export default function FieldsetHelperText({
  className,
  children,
  ...props
}: FieldsetHelperTextProps) {
  return (
    <Ark.HelperText className={cn(styles.helperText(), className)} {...props}>
      {children}
    </Ark.HelperText>
  );
}
