// apps/playground/src/previews/TimerPreview.tsx
import { timer, variantValues } from "@75neo/themes";
import { Timer } from "@75neo/react";

const sizes = variantValues(timer, "size");

const row = "grid gap-2 @sm:grid-cols-[5rem_minmax(0,1fr)] @sm:items-center @sm:gap-4";
const rowLabel = "text-dimmed font-mono text-[0.6875rem] leading-none";

export default function TimerPreview() {
  return (
    <div className="@container flex flex-col gap-6">
      {sizes.map((size) => (
        <div key={size} className={row}>
          <p className={rowLabel} data-identifier>
            {size}
          </p>
          <Timer size={size} controls={false} startMs={12 * 60 * 1000 + 34 * 1000} />
        </div>
      ))}

      <hr className="border-muted" />

      <div className={row}>
        <p className={rowLabel} data-identifier>
          countdown
        </p>
        <Timer countdown startMs={5 * 60 * 1000} targetMs={0} />
      </div>

      <div className={row}>
        <p className={rowLabel} data-identifier>
          labels
        </p>
        <Timer
          units={["hours", "minutes", "seconds"]}
          labels={{ hours: "hrs", minutes: "min", seconds: "sec" }}
          separator="."
        />
      </div>
    </div>
  );
}

// src/components/docs/previews/TimerPreview.vue
<script setup lang="ts">
import Timer from "@/registry/vue/ui/timer/Timer.vue";
import TimerActionTrigger from "@/registry/vue/ui/timer/TimerActionTrigger.vue";
import TimerArea from "@/registry/vue/ui/timer/TimerArea.vue";
import TimerControl from "@/registry/vue/ui/timer/TimerControl.vue";
import TimerItem from "@/registry/vue/ui/timer/TimerItem.vue";
import TimerSeparator from "@/registry/vue/ui/timer/TimerSeparator.vue";
import { TimerContext } from "@ark-ui/vue/timer";

const units = ["hours", "minutes", "seconds"] as const;
</script>

<template>
  <div class="flex flex-col items-center gap-4">
    <Timer :target-ms="90 * 60 * 1000" countdown auto-start>
      <TimerArea>
        <TimerContext v-slot="timer">
          <template v-for="(unit, index) in units" :key="unit">
            <TimerItem :type="unit">
              <span class="font-mono text-lg leading-none text-default tabular-nums">
                {{ timer.formattedTime[unit] }}
              </span>
              <span class="text-[0.625rem] text-dimmed uppercase">{{ unit }}</span>
            </TimerItem>
            <TimerSeparator v-if="index < units.length - 1">:</TimerSeparator>
          </template>
        </TimerContext>
      </TimerArea>

      <TimerControl>
        <TimerActionTrigger action="start">Start</TimerActionTrigger>
        <TimerActionTrigger action="pause">Pause</TimerActionTrigger>
        <TimerActionTrigger action="reset">Reset</TimerActionTrigger>
      </TimerControl>
    </Timer>
  </div>
</template>
