// registry/react/ui/date-picker/DatePickerYearSelect.tsx
import React from "react";
import { DatePicker as Ark } from "@ark-ui/react/date-picker";
import { cn } from "cn";
import { datePickerStyles as styles } from "@/registry/shared/lib/date-picker.styles";

export interface DatePickerYearSelectProps extends Omit<
  React.ComponentPropsWithRef<typeof Ark.YearSelect>,
  "children"
> {}

export default function DatePickerYearSelect({ className, ...props }: DatePickerYearSelectProps) {
  return <Ark.YearSelect className={cn(styles.yearSelect(), className)} {...props} />;
}

// registry/vue/ui/date-picker/DatePickerYearSelect.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { DatePicker as Ark } from "@ark-ui/vue/date-picker";
import { cn } from "cn";
import { datePickerStyles as styles } from "@/registry/shared/lib/date-picker.styles";

interface DatePickerYearSelectProps {
  class?: HTMLAttributes["class"];
}

const props = defineProps<DatePickerYearSelectProps>();
</script>

<template>
  <Ark.YearSelect :class="cn(styles.yearSelect(), props.class)" />
</template>
