// registry/react/ui/clipboard/ClipboardControl.tsx
import React from "react";
import { Clipboard as Ark } from "@ark-ui/react/clipboard";
import { cn } from "cn";
import { clipboardStyles as styles } from "@/registry/shared/lib/clipboard.styles";

export interface ClipboardControlProps extends React.ComponentPropsWithRef<typeof Ark.Control> {}

export default function ClipboardControl({ className, children, ...props }: ClipboardControlProps) {
  return (
    <Ark.Control className={cn(styles.control(), className)} {...props}>
      {children}
    </Ark.Control>
  );
}

// registry/vue/ui/clipboard/ClipboardControl.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { Clipboard as Ark } from "@ark-ui/vue/clipboard";
import { cn } from "cn";
import { clipboardStyles as styles } from "@/registry/shared/lib/clipboard.styles";

interface ClipboardControlProps {
  class?: HTMLAttributes["class"];
}

const props = defineProps<ClipboardControlProps>();

defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <Ark.Control :class="cn(styles.control(), props.class)">
    <slot />
  </Ark.Control>
</template>
