// registry/react/ui/tree-view/TreeViewItem.tsx
import React from "react";
import { TreeView as Ark } from "@ark-ui/react/tree-view";
import { cn } from "cn";
import { treeViewStyles as styles } from "@/registry/shared/lib/tree-view.styles";

export interface TreeViewItemProps extends React.ComponentPropsWithRef<typeof Ark.Item> {}

export default function TreeViewItem({ className, children, ...props }: TreeViewItemProps) {
  return (
    <Ark.Item className={cn(styles.item(), className)} {...props}>
      {children}
    </Ark.Item>
  );
}

// registry/vue/ui/tree-view/TreeViewItem.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { TreeView as Ark } from "@ark-ui/vue/tree-view";
import type { TreeNode } from "@ark-ui/vue/collection";
import { cn } from "cn";
import { treeViewStyles as styles } from "@/registry/shared/lib/tree-view.styles";

interface TreeViewItemProps {
  node: TreeNode;
  indexPath: number[];
  class?: HTMLAttributes["class"];
}

const props = defineProps<TreeViewItemProps>();

defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <Ark.Item
    :node="props.node"
    :index-path="props.indexPath"
    :class="cn(styles.item(), props.class)"
  >
    <slot />
  </Ark.Item>
</template>
