// registry/vue/ui/angle-slider/AngleSliderMarker.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { AngleSlider as Ark } from "@ark-ui/vue/angle-slider";
import { cn } from "cn";
import { angleSliderStyles as styles } from "@/registry/shared/lib/angle-slider.styles";

interface AngleSliderMarkerProps {
  value: number;
  class?: HTMLAttributes["class"];
}

const props = defineProps<AngleSliderMarkerProps>();
</script>

<template>
  <Ark.Marker :value="props.value" :class="cn(styles.marker(), props.class)" />
</template>

// registry/react/ui/angle-slider/AngleSliderMarker.tsx
import React from "react";
import { AngleSlider as Ark } from "@ark-ui/react/angle-slider";
import { cn } from "cn";
import { angleSliderStyles as styles } from "@/registry/shared/lib/angle-slider.styles";

export interface AngleSliderMarkerProps extends Omit<
  React.ComponentPropsWithRef<typeof Ark.Marker>,
  "children"
> {}

export default function AngleSliderMarker({ className, ...props }: AngleSliderMarkerProps) {
  return <Ark.Marker className={cn(styles.marker(), className)} {...props} />;
}
