// packages/vue/src/steps/content.vue
<script setup lang="ts">
import { computed } from "vue";
import { Steps as Ark } from "@ark-ui/vue/steps";
import { cva } from "class-variance-authority";
import { cn, stepsDefaults, stepsSizeData } from "@75neo/themes";
import { useStepsVariants } from "./variants";

const stepsContent = cva("rounded-lg bg-muted text-toned", {
  variants: { size: stepsSizeData.content },
  defaultVariants: stepsDefaults,
});

const props = defineProps<{
  index: number;
  class?: unknown;
}>();

defineSlots<{
  default?: () => unknown;
}>();

const variants = useStepsVariants();
const contentClass = computed(() =>
  cn(stepsContent({ size: variants.size }), props.class as string | undefined),
);
</script>

<template>
  <Ark.Content data-slot="steps-content" :index="props.index" :class="contentClass">
    <slot />
  </Ark.Content>
</template>

// packages/react/src/tabs/content.tsx
import type React from "react";
import { Tabs as Ark } from "@ark-ui/react/tabs";
import { cva } from "class-variance-authority";
import {
  cn,
  tabsDefaults,
  tabsSizeData,
  type TabsContentProps as TabsContentContract,
} from "@75neo/themes";
import { useTabsVariants } from "./variants";

const tabsContent = cva("min-w-0 outline-none", {
  variants: { size: tabsSizeData.content },
  defaultVariants: tabsDefaults,
});

export interface TabsContentProps
  extends
    Omit<React.ComponentProps<typeof Ark.Content>, "value" | "children">,
    TabsContentContract {
  children?: React.ReactNode;
}

export function TabsContent({ value, className, children, ...rest }: TabsContentProps) {
  const variants = useTabsVariants();

  return (
    <Ark.Content
      {...rest}
      value={value}
      data-slot="tabs-content"
      className={cn(tabsContent(variants), className)}
    >
      {children}
    </Ark.Content>
  );
}
