// registry/vue/ui/pin-input/PinInputControl.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { PinInput as Ark } from "@ark-ui/vue/pin-input";
import { cn } from "cn";
import { pinInputStyles as styles } from "@/registry/shared/lib/pin-input.styles";

interface PinInputControlProps {
  class?: HTMLAttributes["class"];
}

const props = defineProps<PinInputControlProps>();

defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <Ark.Control :class="cn(styles.control(), props.class)">
    <slot />
  </Ark.Control>
</template>

// registry/react/ui/pin-input/PinInputControl.tsx
import React from "react";
import { PinInput as Ark } from "@ark-ui/react/pin-input";
import { cn } from "cn";
import { pinInputStyles as styles } from "@/registry/shared/lib/pin-input.styles";

export interface PinInputControlProps extends React.ComponentPropsWithRef<typeof Ark.Control> {}

export default function PinInputControl({ className, children, ...props }: PinInputControlProps) {
  return (
    <Ark.Control className={cn(styles.control(), className)} {...props}>
      {children}
    </Ark.Control>
  );
}
