// packages/react/src/popover/popover.tsx
import type React from "react";
import { Popover as Ark } from "@ark-ui/react/popover";
import { popoverDefaults, type PopoverRootProps as PopoverContract } from "@75neo/themes";
import { PopoverVariantsContext } from "./variants";
import { PopoverArrow } from "./arrow";
import { PopoverBody } from "./body";
import { PopoverCloseTrigger } from "./close-trigger";
import { PopoverContent } from "./content";
import { PopoverDescription } from "./description";
import { PopoverTitle } from "./title";

/**
 * Props for the Popover.
 *
 * @remarks
 * `title` is dropped from the HTML attributes, because the global attribute is the
 * wrong kind of title, and so is `content`. `dir` belongs to the locale provider.
 *
 * The open state comes from Ark, because React and Vue spell a controlled value too
 * differently to share one type.
 *
 * `children` is the trigger, not the body: the body is data, and the one element a
 * caller has to own is what opens the popover.
 */
export interface PopoverProps
  extends
    Omit<React.HTMLAttributes<HTMLDivElement>, "title" | "dir" | "content">,
    Pick<React.ComponentProps<typeof Ark.Root>, "open" | "defaultOpen" | "onOpenChange" | "ids">,
    PopoverContract<React.ReactNode> {
  /** The element that opens the popover. It becomes the trigger. */
  children?: React.ReactNode;
}

export function Popover({
  size,
  title,
  description,
  body,
  arrow = false,
  placement = "bottom",
  offset = 8,
  dismissible,
  modal,
  close = false,
  closeIcon,
  autoFocus,
  portal,
  lazyMount,
  unmountOnExit,
  children,
  open,
  defaultOpen,
  onOpenChange,
  ids,
  className,
  ...rest
}: PopoverProps) {
  const resolved = {
    size: size ?? popoverDefaults.size,
    close,
  };

  /*
   * Ark spells the two halves of dismissal separately, and a caller is thinking
   * about dismissal as one thing. Left `undefined` rather than `true` when it is
   * on, so Ark's own defaults stand. The Dialog does the same.
   */
  const dismiss = dismissible ? undefined : false;

  return (
    <PopoverVariantsContext.Provider value={resolved}>
      <Ark.Root
        {...rest}
        open={open}
        defaultOpen={defaultOpen}
        onOpenChange={onOpenChange}
        closeOnEscape={dismiss}
        closeOnInteractOutside={dismiss}
        modal={modal}
        autoFocus={autoFocus}
        positioning={{ placement, offset: { mainAxis: offset } }}
        lazyMount={lazyMount}
        unmountOnExit={unmountOnExit}
        ids={ids}
        data-slot="popover"
        data-size={resolved.size}
      >
        {children != null && <Ark.Trigger asChild>{children}</Ark.Trigger>}
        <PopoverContent portal={portal} className={className}>
          {arrow && <PopoverArrow />}
          {title != null && <PopoverTitle>{title}</PopoverTitle>}
          {description != null && <PopoverDescription>{description}</PopoverDescription>}
          {body != null && <PopoverBody>{body}</PopoverBody>}
          {close && (
            <PopoverCloseTrigger aria-label="Close popover">{closeIcon}</PopoverCloseTrigger>
          )}
        </PopoverContent>
      </Ark.Root>
    </PopoverVariantsContext.Provider>
  );
}

// packages/vue/src/popover/popover.vue
<script setup lang="ts">
import { type Component, computed, provide, reactive } from "vue";
import { Popover as Ark } from "@ark-ui/vue/popover";
import { X as XIcon } from "@lucide/vue";
import { popoverDefaults, type PopoverRootProps } from "@75neo/themes";
import { popoverVariantsKey } from "./variants";
import PopoverArrow from "./arrow.vue";
import PopoverBody from "./body.vue";
import PopoverCloseTrigger from "./close-trigger.vue";
import PopoverContent from "./content.vue";
import PopoverDescription from "./description.vue";
import PopoverTitle from "./title.vue";

const props = withDefaults(
  defineProps<
    PopoverRootProps<Component> & {
      class?: unknown;
    }
  >(),
  { arrow: false, placement: "bottom", offset: 8, close: false },
);

const emit = defineEmits<{
  /** Fired when the popover opens or closes. */
  openChange: [details: { open: boolean }];
}>();

defineSlots<{
  /** The element that opens the popover. It becomes the trigger. */
  default?: () => unknown;
}>();

/*
 * `default: undefined` keeps an absent `v-model:open` absent. Without it the declared
 * prop would reach Ark as an explicit `false` and pin the popover shut, which would
 * leave `defaultOpen` with nothing to do.
 */
const open = defineModel<boolean | undefined>("open", { default: undefined });

// Getters, so a later prop change reaches already-mounted parts.
const resolved = reactive({
  get size() {
    return props.size ?? popoverDefaults.size;
  },
  get close() {
    return props.close;
  },
});
provide(popoverVariantsKey, resolved);

/*
 * Ark spells the two halves of dismissal separately, and a caller is thinking
 * about dismissal as one thing. Left `undefined` rather than `true` when it is
 * on, so Ark's own defaults stand.
 */
const dismiss = computed(() => ((props.dismissible ?? true) ? undefined : false));
</script>

<template>
  <Ark.Root
    data-slot="popover"
    :data-size="resolved.size"
    v-model:open="open"
    @open-change="emit('openChange', $event)"
    :close-on-escape="dismiss"
    :close-on-interact-outside="dismiss"
    :modal="props.modal"
    :auto-focus="props.autoFocus"
    :positioning="{ placement: props.placement, offset: { mainAxis: props.offset } }"
    :lazy-mount="props.lazyMount"
    :unmount-on-exit="props.unmountOnExit"
  >
    <Ark.Trigger v-if="$slots.default" as-child>
      <slot />
    </Ark.Trigger>
    <PopoverContent :portal="props.portal" :class="props.class as string | undefined">
      <PopoverArrow v-if="props.arrow" />
      <PopoverTitle v-if="props.title != null">{{ props.title }}</PopoverTitle>
      <PopoverDescription v-if="props.description != null">
        {{ props.description }}
      </PopoverDescription>
      <PopoverBody v-if="props.body != null">
        <component :is="props.body" />
      </PopoverBody>
      <PopoverCloseTrigger v-if="props.close" aria-label="Close popover">
        <component :is="props.closeIcon ?? XIcon" />
      </PopoverCloseTrigger>
    </PopoverContent>
  </Ark.Root>
</template>
