// registry/react/ui/date-input/DateInputSegment.tsx
import React from "react";
import { DateInput as Ark } from "@ark-ui/react/date-input";
import { cn } from "cn";
import { dateInput } from "@/registry/shared/lib/date-input.styles";

export interface DateInputSegmentProps extends React.ComponentPropsWithRef<typeof Ark.Segment> {}

export default function DateInputSegment({ className, children, ...props }: DateInputSegmentProps) {
  const styles = dateInput();

  return (
    <Ark.Segment className={cn(styles.segment(), className)} {...props}>
      {children}
    </Ark.Segment>
  );
}

// registry/vue/ui/date-input/DateInputSegment.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { DateInput as Ark } from "@ark-ui/vue/date-input";
import { cn } from "cn";
import { dateInput } from "@/registry/shared/lib/date-input.styles";

interface DateInputSegmentProps {
  class?: HTMLAttributes["class"];
}

const props = defineProps<DateInputSegmentProps>();

defineSlots<{
  default?: () => unknown;
}>();

const styles = dateInput();
</script>

<template>
  <Ark.Segment :class="cn(styles.segment(), props.class)">
    <slot />
  </Ark.Segment>
</template>
