// packages/vue/src/dialog/dialog.vue
<script setup lang="ts">
import { type Component, computed, provide, reactive } from "vue";
import { Dialog as Ark } from "@ark-ui/vue/dialog";
import { X as XIcon } from "@lucide/vue";
import { cn, dialogDefaults, type DialogRootProps } from "@75neo/themes";
import { dialogVariantsKey } from "./variants";
import DialogBackdrop from "./backdrop.vue";
import DialogBody from "./body.vue";
import DialogCloseTrigger from "./close-trigger.vue";
import DialogContent from "./content.vue";
import DialogDescription from "./description.vue";
import DialogFooter from "./footer.vue";
import DialogHeader from "./header.vue";
import DialogTitle from "./title.vue";

const props = defineProps<
  DialogRootProps<Component> & {
    class?: unknown;
  }
>();

const emit = defineEmits<{
  /** Fired when the dialog opens or closes. */
  openChange: [details: { open: boolean }];
}>();

defineSlots<{
  /** The element that opens the dialog. It becomes the trigger. */
  default?: () => unknown;
}>();

/*
 * `default: undefined` keeps an absent `v-model:open` absent. Without it the declared
 * prop would reach Ark as an explicit `false` and pin the dialog shut, which would
 * leave `defaultOpen` with nothing to do.
 */
const open = defineModel<boolean | undefined>("open", { default: undefined });

// Getters, so a later prop change reaches already-mounted parts.
const resolved = reactive({
  get size() {
    return props.size ?? dialogDefaults.size;
  },
});
provide(dialogVariantsKey, resolved);

/*
 * Ark spells the two halves of dismissal separately, and a caller thinking about a
 * confirmation dialog is thinking about both at once, so one prop drives both. Left
 * `undefined` rather than `true` when it is on, so Ark's own defaults stand.
 */
const dismiss = computed(() => ((props.dismissible ?? true) ? undefined : false));
</script>

<template>
  <Ark.Root
    data-slot="dialog"
    :data-size="resolved.size"
    :open="open"
    @open-change="emit('openChange', $event)"
    :close-on-escape="dismiss"
    :close-on-interact-outside="dismiss"
    :modal="props.modal"
    :role="props.role"
    :lazy-mount="props.lazyMount"
    :unmount-on-exit="props.unmountOnExit"
  >
    <Ark.Trigger v-if="$slots.default" as-child>
      <slot />
    </Ark.Trigger>
    <DialogBackdrop v-if="props.overlay ?? true" :transition="props.transition" />
    <DialogContent
      :portal="props.portal"
      :transition="props.transition"
      :fullscreen="props.fullscreen"
      :class="props.class as string | undefined"
    >
      <component :is="props.header" v-if="props.header !== undefined" />
      <template v-else>
        <DialogHeader>
          <span data-slot="dialog-wrapper" :class="cn('flex min-w-0 flex-1 flex-col gap-1')">
            <DialogTitle v-if="props.title != null">{{ props.title }}</DialogTitle>
            <DialogDescription v-if="props.description != null">
              {{ props.description }}
            </DialogDescription>
          </span>
          <DialogCloseTrigger v-if="props.close ?? true" aria-label="Close dialog">
            <component :is="props.closeIcon ?? XIcon" />
          </DialogCloseTrigger>
        </DialogHeader>
        <DialogBody v-if="props.body != null">
          <component :is="props.body" />
        </DialogBody>
        <DialogFooter v-if="props.footer != null">
          <component :is="props.footer" />
        </DialogFooter>
      </template>
    </DialogContent>
  </Ark.Root>
</template>

// packages/react/src/dialog/dialog.tsx
import type React from "react";
import { Dialog as Ark } from "@ark-ui/react/dialog";
import { cn, dialogDefaults, type DialogRootProps as DialogContract } from "@75neo/themes";
import { DialogVariantsContext } from "./variants";
import { DialogBackdrop } from "./backdrop";
import { DialogBody } from "./body";
import { DialogCloseTrigger } from "./close-trigger";
import { DialogContent } from "./content";
import { DialogDescription } from "./description";
import { DialogFooter } from "./footer";
import { DialogHeader } from "./header";
import { DialogTitle } from "./title";

/**
 * Props for the Dialog.
 *
 * @remarks
 * `title` is dropped from the HTML attributes, because the global attribute takes a
 * name, and `role` and `dir` because Ark and the locale provider own them.
 *
 * The open state comes from Ark, because React and Vue spell a controlled value too
 * differently to share one type.
 *
 * `children` is the trigger, not the body: the body is data, and the one element a
 * caller has to own is what opens the dialog.
 */
export interface DialogProps
  extends
    Omit<React.HTMLAttributes<HTMLDivElement>, "title" | "role" | "dir">,
    Pick<React.ComponentProps<typeof Ark.Root>, "open" | "defaultOpen" | "onOpenChange" | "ids">,
    DialogContract<React.ReactNode> {
  /** The element that opens the dialog. It becomes the trigger. */
  children?: React.ReactNode;
}

export function Dialog({
  size,
  transition,
  fullscreen,
  title,
  description,
  header,
  body,
  footer,
  overlay,
  dismissible,
  close,
  closeIcon,
  modal,
  role,
  portal,
  lazyMount,
  unmountOnExit,
  children,
  open,
  defaultOpen,
  onOpenChange,
  ids,
  className,
  ...rest
}: DialogProps) {
  const resolved = { size: size ?? dialogDefaults.size };

  /*
   * Ark spells the two halves of dismissal separately, and a caller thinking about a
   * confirmation dialog is thinking about both at once, so one prop drives both. Left
   * `undefined` rather than `true` when it is on, so Ark's own defaults stand.
   */
  const dismiss = dismissible ? undefined : false;

  return (
    <DialogVariantsContext.Provider value={resolved}>
      <Ark.Root
        {...rest}
        open={open}
        defaultOpen={defaultOpen}
        onOpenChange={onOpenChange}
        closeOnEscape={dismiss}
        closeOnInteractOutside={dismiss}
        modal={modal}
        role={role}
        lazyMount={lazyMount}
        unmountOnExit={unmountOnExit}
        ids={ids}
        data-slot="dialog"
        data-size={resolved.size}
      >
        {children != null && <Ark.Trigger asChild>{children}</Ark.Trigger>}
        {(overlay ?? true) && <DialogBackdrop transition={transition} />}
        <DialogContent
          portal={portal}
          transition={transition}
          fullscreen={fullscreen}
          className={className}
        >
          {header ?? (
            <DialogHeader>
              <span data-slot="dialog-wrapper" className={cn("flex min-w-0 flex-1 flex-col gap-1")}>
                {title != null && <DialogTitle>{title}</DialogTitle>}
                {description != null && <DialogDescription>{description}</DialogDescription>}
              </span>
              {(close ?? true) && (
                <DialogCloseTrigger aria-label="Close dialog">{closeIcon}</DialogCloseTrigger>
              )}
            </DialogHeader>
          )}
          {body != null && <DialogBody>{body}</DialogBody>}
          {footer != null && <DialogFooter>{footer}</DialogFooter>}
        </DialogContent>
      </Ark.Root>
    </DialogVariantsContext.Provider>
  );
}
