// registry/vue/ui/tooltip/TooltipArrowTip.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { Tooltip as Ark } from "@ark-ui/vue/tooltip";
import { cn } from "cn";
import { tooltipStyles as styles } from "@/registry/shared/lib/tooltip.styles";

interface TooltipArrowTipProps {
  class?: HTMLAttributes["class"];
}

const props = defineProps<TooltipArrowTipProps>();
</script>

<template>
  <Ark.ArrowTip :class="cn(styles.arrowTip(), props.class)" />
</template>

// registry/react/ui/tooltip/TooltipArrowTip.tsx
import React from "react";
import { Tooltip as Ark } from "@ark-ui/react/tooltip";
import { cn } from "cn";
import { tooltipStyles as styles } from "@/registry/shared/lib/tooltip.styles";

export interface TooltipArrowTipProps extends React.ComponentPropsWithRef<typeof Ark.ArrowTip> {}

export default function TooltipArrowTip({ className, ...props }: TooltipArrowTipProps) {
  return <Ark.ArrowTip className={cn(styles.arrowTip(), className)} {...props} />;
}
