// registry/vue/ui/marquee/MarqueeEdge.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { Marquee as Ark } from "@ark-ui/vue/marquee";
import type { MarqueeEdgeProps as ArkEdgeProps } from "@ark-ui/vue/marquee";
import { cn } from "cn";
import { marqueeStyles as styles } from "@/registry/shared/lib/marquee.styles";

interface MarqueeEdgeProps {
  side: ArkEdgeProps["side"];
  class?: HTMLAttributes["class"];
}

const props = defineProps<MarqueeEdgeProps>();
</script>

<template>
  <Ark.Edge :side="props.side" :class="cn(styles.edge(), props.class)" />
</template>

// registry/react/ui/marquee/MarqueeEdge.tsx
import React from "react";
import { Marquee as Ark } from "@ark-ui/react/marquee";
import { cn } from "cn";
import { marqueeStyles as styles } from "@/registry/shared/lib/marquee.styles";

export interface MarqueeEdgeProps extends Omit<
  React.ComponentPropsWithRef<typeof Ark.Edge>,
  "children"
> {}

export default function MarqueeEdge({ className, ...props }: MarqueeEdgeProps) {
  return <Ark.Edge className={cn(styles.edge(), className)} {...props} />;
}
