// registry/react/ui/pagination/PaginationEllipsis.tsx
import React from "react";
import { Pagination as Ark } from "@ark-ui/react/pagination";
import { cn } from "cn";
import { paginationStyles as styles } from "@/registry/shared/lib/pagination.styles";

export interface PaginationEllipsisProps extends React.ComponentPropsWithRef<typeof Ark.Ellipsis> {}

export default function PaginationEllipsis({
  className,
  children,
  ...props
}: PaginationEllipsisProps) {
  return (
    <Ark.Ellipsis className={cn(styles.ellipsis(), className)} {...props}>
      {children}
    </Ark.Ellipsis>
  );
}

// registry/vue/ui/pagination/PaginationEllipsis.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { Pagination as Ark } from "@ark-ui/vue/pagination";
import { cn } from "cn";
import { paginationStyles as styles } from "@/registry/shared/lib/pagination.styles";

interface PaginationEllipsisProps {
  index: number;
  class?: HTMLAttributes["class"];
}

const props = defineProps<PaginationEllipsisProps>();

defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <Ark.Ellipsis :index="props.index" :class="cn(styles.ellipsis(), props.class)">
    <slot />
  </Ark.Ellipsis>
</template>
