// registry/vue/ui/signature-pad/SignaturePad.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { SignaturePad as Ark } from "@ark-ui/vue/signature-pad";
import { cn } from "cn";
import { signaturePadStyles as styles } from "@/registry/shared/lib/signature-pad.styles";

interface SignaturePadProps {
  defaultPaths?: string[];
  disabled?: boolean;
  readOnly?: boolean;
  required?: boolean;
  name?: string;
  class?: HTMLAttributes["class"];
}

const props = withDefaults(defineProps<SignaturePadProps>(), {
  disabled: undefined,
  readOnly: undefined,
  required: undefined,
});

const paths = defineModel<string[]>("paths");

defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <Ark.Root
    v-model:paths="paths"
    :default-paths="props.defaultPaths"
    :disabled="props.disabled"
    :read-only="props.readOnly"
    :required="props.required"
    :name="props.name"
    :class="cn(styles.root(), props.class)"
  >
    <slot />
  </Ark.Root>
</template>

// registry/react/ui/signature-pad/SignaturePad.tsx
import React from "react";
import { SignaturePad as Ark } from "@ark-ui/react/signature-pad";
import { cn } from "cn";
import { signaturePadStyles as styles } from "@/registry/shared/lib/signature-pad.styles";

export interface SignaturePadProps extends React.ComponentPropsWithRef<typeof Ark.Root> {}

export default function SignaturePad({ className, children, ...props }: SignaturePadProps) {
  return (
    <Ark.Root className={cn(styles.root(), className)} {...props}>
      {children}
    </Ark.Root>
  );
}
