// registry/vue/ui/signature-pad/SignaturePadSegment.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { SignaturePad as Ark } from "@ark-ui/vue/signature-pad";
import { cn } from "cn";
import { signaturePadStyles as styles } from "@/registry/shared/lib/signature-pad.styles";

interface SignaturePadSegmentProps {
  class?: HTMLAttributes["class"];
}

const props = defineProps<SignaturePadSegmentProps>();
</script>

<template>
  <Ark.Segment :class="cn(styles.segment(), props.class)" />
</template>

// registry/react/ui/signature-pad/SignaturePadSegment.tsx
import React from "react";
import { SignaturePad as Ark } from "@ark-ui/react/signature-pad";
import { cn } from "cn";
import { signaturePadStyles as styles } from "@/registry/shared/lib/signature-pad.styles";

export interface SignaturePadSegmentProps extends Omit<
  React.ComponentPropsWithRef<typeof Ark.Segment>,
  "children"
> {}

export default function SignaturePadSegment({ className, ...props }: SignaturePadSegmentProps) {
  return <Ark.Segment className={cn(styles.segment(), className)} {...props} />;
}
