// registry/vue/ui/color-picker/ColorPickerSwatchTrigger.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { ColorPicker as Ark } from "@ark-ui/vue/color-picker";
import type { Color } from "@ark-ui/vue/color-picker";
import { cn } from "cn";
import { colorPickerStyles as styles } from "@/registry/shared/lib/color-picker.styles";

interface ColorPickerSwatchTriggerProps {
  value: string | Color;
  disabled?: boolean;
  class?: HTMLAttributes["class"];
}

const props = withDefaults(defineProps<ColorPickerSwatchTriggerProps>(), {
  disabled: undefined,
});

defineSlots<{
  default?: () => unknown;
}>();
</script>

<template>
  <Ark.SwatchTrigger
    :value="props.value"
    :disabled="props.disabled"
    :class="cn(styles.swatchTrigger(), props.class)"
  >
    <slot />
  </Ark.SwatchTrigger>
</template>

// registry/react/ui/color-picker/ColorPickerSwatchTrigger.tsx
import React from "react";
import { ColorPicker as Ark } from "@ark-ui/react/color-picker";
import { cn } from "cn";
import { colorPickerStyles as styles } from "@/registry/shared/lib/color-picker.styles";

export interface ColorPickerSwatchTriggerProps extends React.ComponentPropsWithRef<
  typeof Ark.SwatchTrigger
> {}

export default function ColorPickerSwatchTrigger({
  className,
  children,
  ...props
}: ColorPickerSwatchTriggerProps) {
  return (
    <Ark.SwatchTrigger className={cn(styles.swatchTrigger(), className)} {...props}>
      {children}
    </Ark.SwatchTrigger>
  );
}
