// registry/vue/ui/dialog/DialogBackdrop.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue";
import { Dialog as Ark } from "@ark-ui/vue/dialog";
import { cn } from "cn";
import { dialogStyles as styles } from "@/registry/shared/lib/dialog.styles";

interface DialogBackdropProps {
  class?: HTMLAttributes["class"];
}

const props = defineProps<DialogBackdropProps>();
</script>

<template>
  <Ark.Backdrop :class="cn(styles.backdrop(), props.class)" />
</template>

// registry/react/ui/dialog/DialogBackdrop.tsx
import React from "react";
import { Dialog as Ark } from "@ark-ui/react/dialog";
import { cn } from "cn";
import { dialogStyles as styles } from "@/registry/shared/lib/dialog.styles";

export interface DialogBackdropProps extends React.ComponentPropsWithRef<typeof Ark.Backdrop> {}

export default function DialogBackdrop({ className, ...props }: DialogBackdropProps) {
  return <Ark.Backdrop className={cn(styles.backdrop(), className)} {...props} />;
}
