// packages/react/src/download-trigger/download-trigger.tsx
import type React from "react";
import { DownloadTrigger as Ark } from "@ark-ui/react/download-trigger";
import { cva } from "class-variance-authority";
import {
  cn,
  downloadTriggerBaseCompoundData,
  downloadTriggerDefaults,
  downloadTriggerSizeData,
  type DownloadTriggerProps as DownloadTriggerContract,
} from "@75neo/themes";

const downloadTriggerBase = cva(
  "inline-flex cursor-pointer items-center justify-center rounded-md font-medium transition-colors focus-visible:outline-3 disabled:cursor-not-allowed disabled:opacity-75 aria-disabled:cursor-not-allowed aria-disabled:opacity-75",
  {
    variants: {
      variant: { solid: "", outline: "", soft: "", ghost: "" },
      color: {
        primary: "",
        secondary: "",
        success: "",
        info: "",
        warning: "",
        error: "",
        neutral: "",
      },
      size: downloadTriggerSizeData.base,
    },
    compoundVariants: downloadTriggerBaseCompoundData,
    defaultVariants: downloadTriggerDefaults,
  },
);

/**
 * Props for the DownloadTrigger.
 *
 * @remarks
 * `color` is dropped from the HTML attributes: the legacy presentational attribute
 * would collide with the variant of the same name.
 */
export interface DownloadTriggerProps
  extends
    Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, "color">,
    DownloadTriggerContract<React.ReactNode> {}

export function DownloadTrigger({
  variant,
  color,
  size,
  data,
  fileName,
  mimeType,
  leadingIcon,
  trailingIcon,
  disabled,
  className,
  children,
  type = "button",
  ...rest
}: DownloadTriggerProps) {
  return (
    <Ark
      {...rest}
      type={type}
      data-slot="download-trigger"
      data-variant={variant ?? downloadTriggerDefaults.variant}
      data-color={color ?? downloadTriggerDefaults.color}
      data-size={size ?? downloadTriggerDefaults.size}
      className={cn(downloadTriggerBase({ variant, size, color }), className)}
      // The contract spells blobs structurally because `@75neo/themes` typechecks
      // without the DOM library; a real `Blob` or `File` satisfies both spellings.
      data={data as React.ComponentProps<typeof Ark>["data"]}
      fileName={fileName}
      mimeType={mimeType}
      disabled={disabled}
    >
      {leadingIcon != null && (
        <span
          data-slot="download-trigger-leading-icon"
          className={cn(
            "shrink-0 [&>svg]:size-full",
            downloadTriggerSizeData.leadingIcon[size ?? downloadTriggerDefaults.size],
          )}
        >
          {leadingIcon}
        </span>
      )}
      {children != null && (
        <span data-slot="download-trigger-label" className={cn("truncate")}>
          {children}
        </span>
      )}
      {trailingIcon != null && (
        <span
          data-slot="download-trigger-trailing-icon"
          className={cn(
            "shrink-0 [&>svg]:size-full",
            downloadTriggerSizeData.trailingIcon[size ?? downloadTriggerDefaults.size],
          )}
        >
          {trailingIcon}
        </span>
      )}
    </Ark>
  );
}

// packages/vue/src/download-trigger/download-trigger.vue
<script setup lang="ts">
import { type Component, computed } from "vue";
import { DownloadTrigger as Ark } from "@ark-ui/vue/download-trigger";
import { cva } from "class-variance-authority";
import {
  cn,
  downloadTriggerBaseCompoundData,
  downloadTriggerDefaults,
  downloadTriggerSizeData,
  type DownloadTriggerProps,
} from "@75neo/themes";

const downloadTriggerBase = cva(
  "inline-flex cursor-pointer items-center justify-center rounded-md font-medium transition-colors focus-visible:outline-3 disabled:cursor-not-allowed disabled:opacity-75 aria-disabled:cursor-not-allowed aria-disabled:opacity-75",
  {
    variants: {
      variant: { solid: "", outline: "", soft: "", ghost: "" },
      color: {
        primary: "",
        secondary: "",
        success: "",
        info: "",
        warning: "",
        error: "",
        neutral: "",
      },
      size: downloadTriggerSizeData.base,
    },
    compoundVariants: downloadTriggerBaseCompoundData,
    defaultVariants: downloadTriggerDefaults,
  },
);

const props = defineProps<
  DownloadTriggerProps<Component> & {
    class?: unknown;
    type?: "button" | "submit" | "reset";
  }
>();

defineSlots<{
  default?: () => unknown;
}>();

const baseClass = computed(() =>
  cn(
    downloadTriggerBase({
      variant: props.variant,
      size: props.size,
      color: props.color,
    }),
    props.class as string | undefined,
  ),
);
const resolvedSize = computed(() => props.size ?? downloadTriggerDefaults.size);
const leadingClass = computed(() =>
  cn("shrink-0 [&>svg]:size-full", downloadTriggerSizeData.leadingIcon[resolvedSize.value]),
);
const trailingClass = computed(() =>
  cn("shrink-0 [&>svg]:size-full", downloadTriggerSizeData.trailingIcon[resolvedSize.value]),
);
</script>

<template>
  <Ark.Root
    data-slot="download-trigger"
    :class="baseClass"
    :data-variant="props.variant ?? 'solid'"
    :data-size="resolvedSize"
    :data-color="props.color ?? 'primary'"
    :type="props.type ?? 'button'"
    :data="props.data"
    :file-name="props.fileName"
    :mime-type="props.mimeType"
    :disabled="props.disabled"
  >
    <span
      v-if="props.leadingIcon != null"
      data-slot="download-trigger-leading-icon"
      :class="leadingClass"
    >
      <component :is="props.leadingIcon" />
    </span>
    <span v-if="$slots.default" data-slot="download-trigger-label" :class="cn('truncate')">
      <slot />
    </span>
    <span
      v-if="props.trailingIcon != null"
      data-slot="download-trigger-trailing-icon"
      :class="trailingClass"
    >
      <component :is="props.trailingIcon" />
    </span>
  </Ark.Root>
</template>
