// packages/vue/src/floating-panel/content.vue
<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { FloatingPanel as Ark } from "@ark-ui/vue/floating-panel";
import { cva } from "class-variance-authority";
import { cn, type FloatingPanelContentProps } from "@75neo/themes";

const floatingPanelContent = cva(
  "relative flex flex-col overflow-hidden rounded-xl bg-default shadow-lg ring ring-accented outline-none",
  {
    variants: {
      transition: {
        true: "data-[state=closed]:animate-panel-out data-[state=open]:animate-panel-in",
        false: "",
      },
    },
    defaultVariants: { transition: true },
  },
);

const props = withDefaults(
  defineProps<
    FloatingPanelContentProps & {
      class?: unknown;
      /** Render the panel at the end of `body`. @defaultValue `true` */
      portal?: boolean;
    }
  >(),
  { transition: true, portal: true },
);

defineSlots<{
  default?: () => unknown;
}>();

const contentClass = computed(() =>
  cn(floatingPanelContent({ transition: props.transition }), props.class as string | undefined),
);

/*
 * Gates the teleport below. Vue casts an absent Teleport target to nothing during the
 * server pass, so the popup is left in place until the component is mounted.
 */
const mounted = ref(false);
onMounted(() => {
  mounted.value = true;
});
</script>

<template>
  <Teleport to="body" :disabled="!props.portal || !mounted">
    <Ark.Positioner data-slot="floating-panel-positioner" class="z-50">
      <Ark.Content data-slot="floating-panel-content" :class="contentClass">
        <slot />
      </Ark.Content>
    </Ark.Positioner>
  </Teleport>
</template>

// packages/react/src/drawer/content.tsx
import type React from "react";
import { Drawer as Ark } from "@ark-ui/react/drawer";
import { cva } from "class-variance-authority";
import { Portal } from "@ark-ui/react/portal";
import {
  cn,
  drawerDefaults,
  drawerPanelCompoundData,
  drawerPlacementData,
  type DrawerContentProps as DrawerContentContract,
} from "@75neo/themes";
import { useDrawerVariants } from "./variants";

const drawerContent = cva(
  "relative flex min-h-0 min-w-0 flex-col overflow-hidden bg-default shadow-2xl ring ring-accented outline-none",
  {
    variants: {
      placement: drawerPlacementData.base,
      size: {
        sm: "",
        md: "",
        lg: "",
        xl: "",
      },
      transition: {
        true: "data-[state=closed]:animate-panel-out data-[state=open]:animate-panel-in",
        false: "",
      },
    },
    compoundVariants: drawerPanelCompoundData,
    defaultVariants: drawerDefaults,
  },
);

export interface DrawerContentProps
  extends React.ComponentProps<typeof Ark.Content>, DrawerContentContract {
  /** Render the panel at the end of `body`. @defaultValue `true` */
  portal?: boolean;
  draggable?: boolean;
}

export function DrawerContent({
  transition,
  portal,
  draggable,
  className,
  children,
  ...rest
}: DrawerContentProps) {
  const variants = useDrawerVariants();
  const panel = (
    <Ark.Positioner
      data-slot="drawer-positioner"
      className={cn("fixed inset-0 flex", drawerPlacementData.positioner[variants.placement])}
    >
      <Ark.Content
        {...rest}
        draggable={draggable}
        data-slot="drawer-content"
        className={cn(drawerContent({ ...variants, transition }), className)}
      >
        {children}
      </Ark.Content>
    </Ark.Positioner>
  );

  if (portal ?? true) return <Portal>{panel}</Portal>;
  return panel;
}
